'use client'

import { useSyncExternalStore } from 'react'
import Link from 'next/link'
import {
  Crown, RefreshCw, Scroll, FileCode, CalendarClock,
  ShieldCheck, Ban, Lightbulb, AlertTriangle, CheckCircle2,
  XCircle, RotateCcw, ChevronRight, ArrowRight, ArrowDown,
  Clock, Scale, BookOpen, ListChecks, Trophy, Zap,
  Target, ClipboardList, Gauge, Activity, FileText,
  Bug, Eye, Sparkles, Quote, Repeat, Ban as BanIcon,
} from 'lucide-react'

// ─── Types ───────────────────────────────────────────────

type InterceptionAction = 'blocked' | 'returned' | 'approved'

interface InterceptionEntry {
  id: string
  timestamp: string
  engine: string
  engineColor: string
  request: string
  governorQuestion: string
  answer: string
  outcome: string
  action: InterceptionAction
}

interface ThreeLevel {
  level: number
  name: string
  tagline: string
  description: string
  status: string
  lastUpdated: string
  accent: 'fuchsia' | 'cyan' | 'emerald'
  icon: typeof Scroll
}

interface GoldenRule {
  id: string
  title: string
  description: string
  icon: typeof Ban
}

interface GrowthPriority {
  rank: number
  label: string
  weight: 'highest' | 'high' | 'mid' | 'low' | 'lowest'
}

interface QualityGate {
  name: string
  value: string
  target: string
  status: 'pass' | 'warning'
}

interface LoopStep {
  label: string
  icon: typeof Activity
}

// ─── Mock Data ───────────────────────────────────────────

const interceptionFeed: InterceptionEntry[] = [
  {
    id: 'int-1',
    timestamp: '2 min ago',
    engine: 'Growth Engine',
    engineColor: 'text-purple-400',
    request: 'Add new dashboard',
    governorQuestion: 'Do we already have Mission Control?',
    answer: 'Yes',
    outcome: 'REJECTED',
    action: 'blocked',
  },
  {
    id: 'int-2',
    timestamp: '8 min ago',
    engine: 'Product Engine',
    engineColor: 'text-orange-400',
    request: 'Add new module',
    governorQuestion: 'Can this be a tab in existing module?',
    answer: 'Yes',
    outcome: 'REJECTED',
    action: 'blocked',
  },
  {
    id: 'int-3',
    timestamp: '14 min ago',
    engine: 'Engineering Engine',
    engineColor: 'text-cyan-400',
    request: 'Make 12 new components',
    governorQuestion: 'How many can be reused?',
    answer: '9',
    outcome: 'RETURNED FOR REFACTOR',
    action: 'returned',
  },
  {
    id: 'int-4',
    timestamp: '23 min ago',
    engine: 'Documentation Engine',
    engineColor: 'text-emerald-400',
    request: 'Add 3 missing API docs',
    governorQuestion: 'Does it improve documentation coverage?',
    answer: 'Yes',
    outcome: 'APPROVED',
    action: 'approved',
  },
  {
    id: 'int-5',
    timestamp: '41 min ago',
    engine: 'Growth Engine',
    engineColor: 'text-purple-400',
    request: 'Add analytics tab to /control',
    governorQuestion: 'Does Analytics page already exist?',
    answer: 'Yes',
    outcome: 'REJECTED',
    action: 'blocked',
  },
  {
    id: 'int-6',
    timestamp: '57 min ago',
    engine: 'Tech Debt Engine',
    engineColor: 'text-rose-400',
    request: 'Remove 3 dead API routes',
    governorQuestion: 'Does it reduce complexity?',
    answer: 'Yes',
    outcome: 'APPROVED',
    action: 'approved',
  },
  {
    id: 'int-7',
    timestamp: '1h 12m ago',
    engine: 'Product Engine',
    engineColor: 'text-orange-400',
    request: 'Add chat widget',
    governorQuestion: 'Is there evidence users need this?',
    answer: 'No',
    outcome: 'REJECTED',
    action: 'blocked',
  },
  {
    id: 'int-8',
    timestamp: '1h 38m ago',
    engine: 'Engineering Engine',
    engineColor: 'text-cyan-400',
    request: 'Rewrite Opportunity Queue',
    governorQuestion: 'Can it be extended instead?',
    answer: 'Yes',
    outcome: 'RETURNED',
    action: 'returned',
  },
]

const threeLevels: ThreeLevel[] = [
  {
    level: 1,
    name: 'Constitution',
    tagline: 'Never changes. The Ustav.',
    description: 'The immutable foundation. Defines non-negotiable principles every engine, every task, every change must obey. Locked at v1.0.0 — amendments require override.',
    status: 'Immutable · Locked',
    lastUpdated: 'Day 0',
    accent: 'fuchsia',
    icon: Scroll,
  },
  {
    level: 2,
    name: 'Master Specification',
    tagline: '300+ pages. Everything.',
    description: 'The living document. Captures every architectural decision, schema, module boundary, and convention. Updated as the system evolves — but never in conflict with Level 1.',
    status: 'Living Document',
    lastUpdated: '6h ago',
    accent: 'cyan',
    icon: FileCode,
  },
  {
    level: 3,
    name: 'Daily Mission',
    tagline: 'Every morning. Scheduler generates.',
    description: 'Today\'s mission. Generated by the Scheduler Engine each morning based on KPIs, opportunities, and Master Spec constraints. Every approved change must trace back here.',
    status: 'Generated Today',
    lastUpdated: '3h ago',
    accent: 'emerald',
    icon: CalendarClock,
  },
]

const decisionFramework: string[] = [
  'Does this solve a real problem?',
  'Is there evidence?',
  'Does it fit the architecture?',
  'Can an existing module solve it?',
  'Will it improve a KPI?',
  'Can it be measured?',
]

const goldenRules: GoldenRule[] = [
  {
    id: 'gr-1',
    title: 'Never create features because they are interesting',
    description: 'Curiosity is not a KPI. Only build with evidence of real need — measured demand, user signal, or strategic alignment.',
    icon: Sparkles,
  },
  {
    id: 'gr-2',
    title: 'Never duplicate functionality',
    description: 'Extend existing systems first. If a similar capability exists, the default answer is to expand it — not to fork it.',
    icon: Ban,
  },
  {
    id: 'gr-3',
    title: 'Never publish simulated research',
    description: 'Observatory credibility is sacred. Simulated or fabricated data is grounds for immediate rejection and rollback.',
    icon: FileText,
  },
  {
    id: 'gr-4',
    title: 'Never reduce documentation coverage',
    description: 'Documentation coverage is monotonic. Any change that lowers coverage — even temporarily — is blocked at the gate.',
    icon: BookOpen,
  },
  {
    id: 'gr-5',
    title: 'Never reduce QA coverage',
    description: 'QA coverage is monotonic. New code without tests is rejected. Existing tests may not be deleted without replacement.',
    icon: ShieldCheck,
  },
  {
    id: 'gr-6',
    title: 'Never reduce Observatory credibility',
    description: 'The Observatory is the source of truth. No engine may write to it without confidence threshold and provenance metadata.',
    icon: Eye,
  },
  {
    id: 'gr-7',
    title: 'Never push directly to production',
    description: 'No exceptions. Every change passes through Review, Merge, Deploy engines. Direct-to-prod commits trigger automatic rollback.',
    icon: Ban,
  },
]

const growthPriorities: GrowthPriority[] = [
  { rank: 1, label: 'Improve existing features', weight: 'highest' },
  { rank: 2, label: 'Remove unnecessary complexity', weight: 'high' },
  { rank: 3, label: 'Increase automation', weight: 'mid' },
  { rank: 4, label: 'Increase documentation', weight: 'low' },
  { rank: 5, label: 'Only then create new features', weight: 'lowest' },
]

const qualityGates: QualityGate[] = [
  { name: 'Code Quality', value: '96', target: 'target 95+', status: 'pass' },
  { name: 'QA Coverage', value: '100%', target: 'target 100%', status: 'pass' },
  { name: 'Documentation', value: '97%', target: 'target 100%', status: 'warning' },
  { name: 'Performance', value: 'No regression', target: 'baseline hold', status: 'pass' },
  { name: 'Accessibility', value: 'AA', target: 'WCAG AA', status: 'pass' },
  { name: 'Research', value: 'Confidence Gate', target: '>0.8', status: 'pass' },
  { name: 'Observatory', value: 'No simulated data', target: 'provenance enforced', status: 'pass' },
]

const developmentLoop: LoopStep[] = [
  { label: 'Observe', icon: Eye },
  { label: 'Discover', icon: Target },
  { label: 'Prioritize', icon: ListChecks },
  { label: 'Design', icon: FileCode },
  { label: 'Implement', icon: Zap },
  { label: 'Test', icon: Bug },
  { label: 'Document', icon: BookOpen },
  { label: 'Deploy Candidate', icon: ArrowRight },
  { label: 'Measure', icon: Gauge },
  { label: 'Learn', icon: Activity },
  { label: 'Repeat', icon: Repeat },
]

// ─── Helpers ─────────────────────────────────────────────

const AUTHORITY_SCORE = 100

function interceptionConfig(action: InterceptionAction) {
  switch (action) {
    case 'blocked': return { color: 'text-red-400', bg: 'bg-red-500/15', border: 'border-red-500/20', icon: XCircle, label: 'BLOCKED' }
    case 'returned': return { color: 'text-amber-400', bg: 'bg-amber-500/15', border: 'border-amber-500/20', icon: RotateCcw, label: 'RETURNED' }
    case 'approved': return { color: 'text-emerald-400', bg: 'bg-emerald-500/15', border: 'border-emerald-500/20', icon: CheckCircle2, label: 'APPROVED' }
  }
}

function levelAccentConfig(accent: ThreeLevel['accent']) {
  switch (accent) {
    case 'fuchsia': return { color: 'text-fuchsia-400', bg: 'bg-fuchsia-500/15', border: 'border-fuchsia-500/20', dot: 'bg-fuchsia-400', gauge: '#e879f9' }
    case 'cyan': return { color: 'text-cyan-400', bg: 'bg-cyan-500/15', border: 'border-cyan-500/20', dot: 'bg-cyan-400', gauge: '#22d3ee' }
    case 'emerald': return { color: 'text-emerald-400', bg: 'bg-emerald-500/15', border: 'border-emerald-500/20', dot: 'bg-emerald-400', gauge: '#34d399' }
  }
}

function priorityWeightConfig(weight: GrowthPriority['weight']) {
  switch (weight) {
    case 'highest': return { color: 'text-fuchsia-400', bg: 'bg-fuchsia-500/15', border: 'border-fuchsia-500/30', label: 'HIGHEST' }
    case 'high': return { color: 'text-cyan-400', bg: 'bg-cyan-500/15', border: 'border-cyan-500/30', label: 'HIGH' }
    case 'mid': return { color: 'text-emerald-400', bg: 'bg-emerald-500/15', border: 'border-emerald-500/30', label: 'MID' }
    case 'low': return { color: 'text-amber-400', bg: 'bg-amber-500/15', border: 'border-amber-500/30', label: 'LOW' }
    case 'lowest': return { color: 'text-slate-400', bg: 'bg-slate-700/40', border: 'border-slate-600/40', label: 'LOWEST' }
  }
}

// ─── Fuchsia Circular Gauge ──────────────────────────────

function CircularGauge({ score, size = 160 }: { score: number; size?: number }) {
  const strokeWidth = 10
  const radius = (size - strokeWidth) / 2
  const circumference = 2 * Math.PI * radius
  const offset = circumference - (score / 100) * circumference
  const center = size / 2

  return (
    <div className="relative" style={{ width: size, height: size }}>
      <svg width={size} height={size} className="-rotate-90">
        {/* Track */}
        <circle
          cx={center}
          cy={center}
          r={radius}
          fill="none"
          stroke="#1e293b"
          strokeWidth={strokeWidth}
        />
        {/* Progress */}
        <circle
          cx={center}
          cy={center}
          r={radius}
          fill="none"
          stroke="#e879f9"
          strokeWidth={strokeWidth}
          strokeLinecap="round"
          strokeDasharray={circumference}
          strokeDashoffset={offset}
          className="transition-all duration-1000 ease-out"
        />
      </svg>
      {/* Center text */}
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <span className="text-4xl font-bold text-fuchsia-400">{score}%</span>
        <span className="text-[10px] text-slate-500 mt-0.5 uppercase tracking-wider">Constitution</span>
      </div>
    </div>
  )
}

// ─── Hydration Guard ─────────────────────────────────────

const emptySubscribe = () => () => {}
function useHydrated() {
  return useSyncExternalStore(emptySubscribe, () => true, () => false)
}

// ─── Main Component ──────────────────────────────────────

export default function GovernorPage() {
  const mounted = useHydrated()

  if (!mounted) return null

  const blockedCount = interceptionFeed.filter(i => i.action === 'blocked').length
  const returnedCount = interceptionFeed.filter(i => i.action === 'returned').length
  const approvedCount = interceptionFeed.filter(i => i.action === 'approved').length
  const warningGates = qualityGates.filter(g => g.status === 'warning').length

  return (
    <div className="space-y-6">

      {/* ═══════════════════════════════════════════════════════
          1. Header
          ═══════════════════════════════════════════════════════ */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-fuchsia-500/15 flex items-center justify-center border border-fuchsia-500/20">
            <Crown className="w-5 h-5 text-fuchsia-400" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-white">AI Governor™</h1>
            <p className="text-slate-400 text-sm">Supreme Authority — Constitution Enforcer</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-fuchsia-500/10 border border-fuchsia-500/20">
            <div className="w-2 h-2 rounded-full bg-fuchsia-400 animate-pulse" />
            <span className="text-xs font-medium text-fuchsia-400">Active</span>
          </div>
          <Link
            href="/control/governor/constitution"
            className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-slate-800 border border-slate-700 text-slate-300 hover:text-white hover:border-fuchsia-500/40 transition-colors text-xs"
          >
            <Scroll className="w-3.5 h-3.5" />
            View Constitution
          </Link>
        </div>
      </div>

      {/* ═══════════════════════════════════════════════════════
          2. Authority Score Banner
          ═══════════════════════════════════════════════════════ */}
      <div className="bg-gradient-to-br from-fuchsia-500/5 via-slate-900 to-slate-900 border border-fuchsia-500/15 rounded-xl p-6">
        <div className="flex flex-col md:flex-row items-center gap-8">
          {/* Circular Gauge */}
          <div className="flex-shrink-0">
            <CircularGauge score={AUTHORITY_SCORE} size={160} />
            <div className="text-center mt-2">
              <span className="text-[10px] text-slate-500 uppercase tracking-wider">Authority Score</span>
            </div>
          </div>

          {/* 6 Stat Boxes */}
          <div className="flex-1 grid grid-cols-2 sm:grid-cols-3 gap-4 w-full">
            <div className="bg-slate-800/50 border border-slate-700/50 rounded-lg p-4 text-center">
              <div className="flex items-center justify-center gap-1.5 mb-1">
                <Ban className="w-4 h-4 text-red-400" />
                <span className="text-2xl font-bold text-red-400">847</span>
              </div>
              <div className="text-[10px] text-slate-500 uppercase tracking-wider">Tasks Intercepted</div>
            </div>
            <div className="bg-slate-800/50 border border-slate-700/50 rounded-lg p-4 text-center">
              <div className="flex items-center justify-center gap-1.5 mb-1">
                <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                <span className="text-2xl font-bold text-emerald-400">312</span>
              </div>
              <div className="text-[10px] text-slate-500 uppercase tracking-wider">Tasks Approved</div>
            </div>
            <div className="bg-slate-800/50 border border-slate-700/50 rounded-lg p-4 text-center">
              <div className="flex items-center justify-center gap-1.5 mb-1">
                <AlertTriangle className="w-4 h-4 text-amber-400" />
                <span className="text-2xl font-bold text-amber-400">73%</span>
              </div>
              <div className="text-[10px] text-slate-500 uppercase tracking-wider">Rejection Rate</div>
            </div>
            <div className="bg-slate-800/50 border border-slate-700/50 rounded-lg p-4 text-center">
              <div className="flex items-center justify-center gap-1.5 mb-1">
                <ShieldCheck className="w-4 h-4 text-fuchsia-400" />
                <span className="text-2xl font-bold text-fuchsia-400">1,204</span>
              </div>
              <div className="text-[10px] text-slate-500 uppercase tracking-wider">Violations Prevented</div>
            </div>
            <div className="bg-slate-800/50 border border-slate-700/50 rounded-lg p-4 text-center">
              <div className="flex items-center justify-center gap-1.5 mb-1">
                <Scale className="w-4 h-4 text-fuchsia-400" />
                <span className="text-sm font-bold text-fuchsia-400">v1.0.0</span>
              </div>
              <div className="text-[10px] text-slate-500 uppercase tracking-wider">Constitution Version</div>
            </div>
            <div className="bg-slate-800/50 border border-slate-700/50 rounded-lg p-4 text-center">
              <div className="flex items-center justify-center gap-1.5 mb-1">
                <Clock className="w-4 h-4 text-cyan-400" />
                <span className="text-2xl font-bold text-cyan-400">247</span>
              </div>
              <div className="text-[10px] text-slate-500 uppercase tracking-wider">Days Active</div>
            </div>
          </div>
        </div>
      </div>

      {/* ═══════════════════════════════════════════════════════
          3. The Three Levels
          ═══════════════════════════════════════════════════════ */}
      <div>
        <h2 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
          <Scale className="w-4 h-4 text-fuchsia-400" />
          The Three Levels
          <span className="ml-auto text-[10px] text-slate-400 uppercase tracking-wider">Constitution → Master Spec → Daily Mission</span>
        </h2>
        <div className="space-y-3">
          {threeLevels.map((level) => {
            const config = levelAccentConfig(level.accent)
            const LevelIcon = level.icon
            // Level 1 is biggest (top), then progressively smaller
            const sizeClass = level.level === 1 ? 'p-5' : level.level === 2 ? 'p-4 ml-4' : 'p-4 ml-8'
            return (
              <div
                key={level.level}
                className={`bg-slate-900 border rounded-xl ${sizeClass} hover:border-slate-700 transition-all duration-200 ${config.border}`}
              >
                <div className="flex items-start gap-4">
                  {/* Level number badge */}
                  <div className={`w-12 h-12 rounded-lg flex items-center justify-center flex-shrink-0 ${config.bg} border ${config.border}`}>
                    <span className={`text-lg font-bold ${config.color}`}>{level.level}</span>
                  </div>

                  {/* Level icon */}
                  <div className={`w-9 h-9 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5 ${config.bg}`}>
                    <LevelIcon className={`w-4 h-4 ${config.color}`} />
                  </div>

                  {/* Content */}
                  <div className="flex-1 min-w-0">
                    <div className="flex flex-wrap items-baseline gap-2 mb-1">
                      <span className="text-base font-bold text-white">{level.name}</span>
                      <span className={`text-xs italic ${config.color}`}>— {level.tagline}</span>
                    </div>
                    <p className="text-xs text-slate-400 leading-relaxed mb-3">{level.description}</p>
                    <div className="flex items-center gap-4 text-[10px]">
                      <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded border ${config.bg} ${config.color} ${config.border} font-medium uppercase tracking-wider`}>
                        <div className={`w-1.5 h-1.5 rounded-full ${config.dot}`} />
                        {level.status}
                      </span>
                      <span className="flex items-center gap-1 text-slate-500">
                        <Clock className="w-3 h-3" />
                        Last updated: <span className="text-slate-400">{level.lastUpdated}</span>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      </div>

      {/* ═══════════════════════════════════════════════════════
          4. Decision Framework — The 6 Questions
          ═══════════════════════════════════════════════════════ */}
      <div>
        <h2 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
          <ShieldCheck className="w-4 h-4 text-fuchsia-400" />
          Decision Framework
          <span className="ml-auto text-[10px] text-slate-400 uppercase tracking-wider">Every task must pass all 6</span>
        </h2>
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
          <div className="space-y-2">
            {decisionFramework.map((question, idx) => (
              <div key={idx} className="flex items-center gap-3">
                <div className="w-7 h-7 rounded-full bg-fuchsia-500/10 border border-fuchsia-500/20 flex items-center justify-center flex-shrink-0">
                  <span className="text-xs font-bold text-fuchsia-400">{idx + 1}</span>
                </div>
                <span className="text-sm text-slate-200 flex-1">{question}</span>
                {idx < decisionFramework.length - 1 && (
                  <ArrowDown className="w-3 h-3 text-slate-600 flex-shrink-0 hidden sm:block" />
                )}
              </div>
            ))}
          </div>

          {/* Red callout */}
          <div className="mt-5 bg-red-500/10 border border-red-500/30 rounded-lg p-4 flex items-start gap-3">
            <div className="w-8 h-8 rounded-lg bg-red-500/15 border border-red-500/20 flex items-center justify-center flex-shrink-0">
              <XCircle className="w-4 h-4 text-red-400" />
            </div>
            <div>
              <div className="text-[10px] text-red-400 uppercase tracking-wider mb-0.5 font-medium">Rejection Rule</div>
              <p className="text-sm text-red-300">
                If <span className="font-bold">any</span> answer is <span className="font-bold">NO</span> → <span className="font-bold">Reject the task</span>. No exceptions, no overrides, no &quot;just this once&quot;.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* ═══════════════════════════════════════════════════════
          5. Golden Rules
          ═══════════════════════════════════════════════════════ */}
      <div>
        <h2 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
          <Crown className="w-4 h-4 text-fuchsia-400" />
          Golden Rules
          <span className="ml-auto text-[10px] text-slate-400 uppercase tracking-wider">{goldenRules.length} non-negotiable</span>
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {goldenRules.map((rule, idx) => {
            const RuleIcon = rule.icon
            return (
              <div
                key={rule.id}
                className="bg-slate-900 border border-slate-800 rounded-xl p-4 hover:border-fuchsia-500/30 transition-all duration-200 group"
              >
                <div className="flex items-start gap-3">
                  <div className="w-9 h-9 rounded-lg bg-red-500/10 border border-red-500/20 flex items-center justify-center flex-shrink-0">
                    <RuleIcon className="w-4 h-4 text-red-400" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-start gap-2 mb-1">
                      <span className="text-[10px] font-bold text-red-400 px-1.5 py-0.5 rounded bg-red-500/10 border border-red-500/20 flex-shrink-0 mt-0.5">NEVER</span>
                      <span className="text-sm font-medium text-white leading-snug">{rule.title}</span>
                    </div>
                    <p className="text-[11px] text-slate-400 leading-relaxed">{rule.description}</p>
                  </div>
                  <span className="text-[10px] text-slate-600 font-mono flex-shrink-0">#{idx + 1}</span>
                </div>
              </div>
            )
          })}
        </div>
      </div>

      {/* ═══════════════════════════════════════════════════════
          6. Live Interception Feed
          ═══════════════════════════════════════════════════════ */}
      <div>
        <div className="flex items-center gap-2 mb-3">
          <h2 className="text-sm font-semibold text-white flex items-center gap-2">
            <Activity className="w-4 h-4 text-fuchsia-400" />
            Live Interception Feed
          </h2>
          <span className="text-[10px] text-slate-500 uppercase tracking-wider">Every task passes through here</span>
          <div className="ml-auto flex items-center gap-3 text-[10px]">
            <span className="flex items-center gap-1 text-slate-400">
              <XCircle className="w-3 h-3 text-red-400" />
              {blockedCount} blocked
            </span>
            <span className="flex items-center gap-1 text-slate-400">
              <RotateCcw className="w-3 h-3 text-amber-400" />
              {returnedCount} returned
            </span>
            <span className="flex items-center gap-1 text-slate-400">
              <CheckCircle2 className="w-3 h-3 text-emerald-400" />
              {approvedCount} approved
            </span>
          </div>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
          <div className="space-y-3 max-h-[640px] overflow-y-auto custom-scrollbar pr-1">
            {interceptionFeed.map((entry) => {
              const config = interceptionConfig(entry.action)
              const ActionIcon = config.icon
              return (
                <div
                  key={entry.id}
                  className={`relative pl-8 pb-4 border-l-2 ${entry.action === 'blocked' ? 'border-red-500/20' : entry.action === 'returned' ? 'border-amber-500/20' : 'border-emerald-500/20'}`}
                >
                  {/* Timeline dot */}
                  <div className={`absolute -left-[9px] top-0 w-4 h-4 rounded-full border-2 border-slate-900 ${config.bg} flex items-center justify-center`}>
                    <div className={`w-1.5 h-1.5 rounded-full ${entry.action === 'blocked' ? 'bg-red-400' : entry.action === 'returned' ? 'bg-amber-400' : 'bg-emerald-400'}`} />
                  </div>

                  {/* Header row */}
                  <div className="flex flex-wrap items-center gap-2 mb-2">
                    <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold border ${config.bg} ${config.color} ${config.border}`}>
                      <ActionIcon className="w-3 h-3" />
                      {config.label}
                    </span>
                    <span className="text-[11px] text-slate-500 flex items-center gap-1">
                      <Clock className="w-3 h-3" />
                      {entry.timestamp}
                    </span>
                    <span className="text-[10px] text-slate-600">·</span>
                    <span className={`text-[11px] font-medium ${entry.engineColor}`}>{entry.engine}</span>
                  </div>

                  {/* Request + Governor reasoning */}
                  <div className="grid grid-cols-1 lg:grid-cols-3 gap-2 text-[11px]">
                    <div className="bg-slate-800/50 border border-slate-700/40 rounded-lg p-2">
                      <div className="text-[9px] text-slate-500 uppercase tracking-wider mb-0.5">Engine Requested</div>
                      <div className="text-slate-200">&quot;{entry.request}&quot;</div>
                    </div>
                    <div className="bg-slate-800/50 border border-fuchsia-500/20 rounded-lg p-2">
                      <div className="text-[9px] text-fuchsia-400 uppercase tracking-wider mb-0.5">Governor Asked</div>
                      <div className="text-slate-200">{entry.governorQuestion}</div>
                    </div>
                    <div className="bg-slate-800/50 border border-slate-700/40 rounded-lg p-2">
                      <div className="text-[9px] text-slate-500 uppercase tracking-wider mb-0.5">Answer → Outcome</div>
                      <div className="text-slate-300">
                        <span className="text-white font-medium">{entry.answer}</span>
                        <ArrowRight className="inline w-3 h-3 mx-1 text-slate-500" />
                        <span className={`font-bold ${config.color}`}>{entry.outcome}</span>
                      </div>
                    </div>
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      </div>

      {/* ═══════════════════════════════════════════════════════
          7. Growth Priorities
          ═══════════════════════════════════════════════════════ */}
      <div>
        <h2 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
          <Trophy className="w-4 h-4 text-fuchsia-400" />
          Growth Priorities
          <span className="ml-auto text-[10px] text-slate-400 uppercase tracking-wider">Ranked — 1 is highest</span>
        </h2>
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
          <div className="space-y-2">
            {growthPriorities.map((priority, idx) => {
              const config = priorityWeightConfig(priority.weight)
              return (
                <div key={priority.rank} className="flex items-center gap-3">
                  {/* Rank number */}
                  <div className={`w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 ${config.bg} border ${config.border}`}>
                    <span className={`text-base font-bold ${config.color}`}>{priority.rank}</span>
                  </div>

                  {/* Label */}
                  <span className="text-sm text-slate-200 flex-1 font-medium">{priority.label}</span>

                  {/* Weight badge */}
                  <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold border ${config.bg} ${config.color} ${config.border}`}>
                    {config.label}
                  </span>

                  {/* Arrow indicator (descending priority) */}
                  {idx < growthPriorities.length - 1 && (
                    <ChevronRight className="w-4 h-4 text-slate-600 flex-shrink-0 rotate-90" />
                  )}
                </div>
              )
            })}
          </div>
          <div className="mt-4 pt-3 border-t border-slate-800 text-[10px] text-slate-500 flex items-center gap-2">
            <AlertTriangle className="w-3 h-3 text-amber-400" />
            New features are a <span className="text-amber-400 font-medium">last resort</span> — never the default.
          </div>
        </div>
      </div>

      {/* ═══════════════════════════════════════════════════════
          8. Quality Gates Status
          ═══════════════════════════════════════════════════════ */}
      <div>
        <h2 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
          <ShieldCheck className="w-4 h-4 text-fuchsia-400" />
          Quality Gates Status
          <span className="ml-auto text-[10px] text-slate-400 uppercase tracking-wider">
            {qualityGates.length - warningGates} passing · {warningGates} attention
          </span>
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
          {qualityGates.map((gate) => {
            const pass = gate.status === 'pass'
            return (
              <div
                key={gate.name}
                className={`bg-slate-900 border rounded-lg p-4 ${pass ? 'border-slate-800' : 'border-amber-500/30'}`}
              >
                <div className="flex items-center justify-between mb-2">
                  <span className="text-[10px] text-slate-500 uppercase tracking-wider">{gate.name}</span>
                  {pass ? (
                    <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                  ) : (
                    <AlertTriangle className="w-4 h-4 text-amber-400" />
                  )}
                </div>
                <div className={`text-lg font-bold ${pass ? 'text-white' : 'text-amber-400'}`}>{gate.value}</div>
                <div className="text-[10px] text-slate-500 mt-0.5">{gate.target}</div>
              </div>
            )
          })}
        </div>
      </div>

      {/* ═══════════════════════════════════════════════════════
          9. Core Rule Callout + Daily Mission Preview (two columns)
          ═══════════════════════════════════════════════════════ */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">

        {/* Core Rule Callout */}
        <div className="bg-gradient-to-br from-fuchsia-500/10 via-slate-900 to-slate-900 border border-fuchsia-500/30 rounded-xl p-5 flex flex-col justify-between">
          <div className="flex items-start gap-3 mb-3">
            <div className="w-10 h-10 rounded-lg bg-fuchsia-500/15 border border-fuchsia-500/30 flex items-center justify-center flex-shrink-0">
              <Crown className="w-5 h-5 text-fuchsia-400" />
            </div>
            <div>
              <div className="text-[10px] text-fuchsia-400 uppercase tracking-wider font-bold mb-1">Core Rule</div>
              <div className="text-xs text-slate-400">The one rule above all others</div>
            </div>
          </div>
          <blockquote className="text-base text-white font-medium leading-relaxed">
            &quot;Every change must improve at least <span className="text-fuchsia-400">one measurable KPI</span>. If no measurable improvement exists, <span className="text-fuchsia-400">do nothing</span>.&quot;
          </blockquote>
          <div className="mt-3 pt-3 border-t border-fuchsia-500/10 flex items-center gap-2 text-[10px] text-slate-500">
            <Scale className="w-3 h-3 text-fuchsia-400" />
            Constitution Level 1 — Article I
          </div>
        </div>

        {/* Daily Mission Preview */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">
              <ClipboardList className="w-4 h-4 text-emerald-400" />
              <h3 className="text-sm font-semibold text-white">Today&apos;s Daily Mission</h3>
            </div>
            <span className="text-[10px] text-emerald-400 px-2 py-0.5 rounded bg-emerald-500/10 border border-emerald-500/20">Level 3</span>
          </div>

          <div className="space-y-2 text-xs">
            <div className="flex items-start gap-2">
              <Target className="w-3.5 h-3.5 text-emerald-400 flex-shrink-0 mt-0.5" />
              <div>
                <span className="text-slate-500">Goal:</span>{' '}
                <span className="text-white font-medium">&quot;Increase activation&quot;</span>
              </div>
            </div>
            <div className="flex items-start gap-2">
              <Activity className="w-3.5 h-3.5 text-cyan-400 flex-shrink-0 mt-0.5" />
              <div>
                <span className="text-slate-500">Strategy:</span>{' '}
                <span className="text-slate-300">Find highest-impact improvement</span>
              </div>
            </div>
            <div className="flex items-start gap-2">
              <ShieldCheck className="w-3.5 h-3.5 text-fuchsia-400 flex-shrink-0 mt-0.5" />
              <div>
                <span className="text-slate-500">Confidence threshold:</span>{' '}
                <span className="text-fuchsia-400 font-mono">&gt;0.8</span>
              </div>
            </div>
            <div className="flex items-start gap-2">
              <Clock className="w-3.5 h-3.5 text-amber-400 flex-shrink-0 mt-0.5" />
              <div>
                <span className="text-slate-500">Budget:</span>{' '}
                <span className="text-slate-300">4 hours, 2 components max, 5 pages max</span>
              </div>
            </div>
            <div className="flex items-start gap-2">
              <ListChecks className="w-3.5 h-3.5 text-emerald-400 flex-shrink-0 mt-0.5" />
              <div>
                <span className="text-slate-500">Must:</span>{' '}
                <span className="text-slate-300">run full QA, update docs, prepare PR, wait for approval</span>
              </div>
            </div>
          </div>

          <Link
            href="/control/governor/daily-mission"
            className="mt-4 flex items-center justify-center gap-2 w-full px-3 py-2 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 hover:bg-emerald-500/15 transition-colors text-xs font-medium"
          >
            View Full Daily Mission
            <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        </div>
      </div>

      {/* ═══════════════════════════════════════════════════════
          10. Development Loop
          ═══════════════════════════════════════════════════════ */}
      <div>
        <h2 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
          <Repeat className="w-4 h-4 text-fuchsia-400" />
          Development Loop
          <span className="ml-auto text-[10px] text-slate-400 uppercase tracking-wider">Continuous · autonomous · measured</span>
        </h2>
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
          <div className="flex flex-wrap items-center gap-2 justify-center">
            {developmentLoop.map((step, idx) => {
              const StepIcon = step.icon
              const isLast = idx === developmentLoop.length - 1
              return (
                <div key={step.label} className="flex items-center gap-2">
                  <div className="flex flex-col items-center gap-1.5 px-3 py-2.5 rounded-lg bg-slate-800/50 border border-slate-700/50 hover:border-fuchsia-500/30 transition-colors min-w-[88px]">
                    <StepIcon className="w-4 h-4 text-fuchsia-400" />
                    <span className="text-[10px] text-slate-300 font-medium text-center">{step.label}</span>
                  </div>
                  {!isLast && (
                    <ArrowRight className="w-3.5 h-3.5 text-slate-600 flex-shrink-0" />
                  )}
                </div>
              )
            })}
          </div>
          <div className="mt-4 pt-3 border-t border-slate-800 text-center text-[10px] text-slate-500">
            Every cycle through this loop must produce measurable improvement — or the loop halts.
          </div>
        </div>
      </div>

      {/* ═══════════════════════════════════════════════════════
          11. Footer Quote Callout
          ═══════════════════════════════════════════════════════ */}
      <div className="bg-gradient-to-r from-fuchsia-500/5 via-slate-900 to-slate-900 border border-fuchsia-500/15 rounded-xl p-5">
        <div className="flex items-start gap-3">
          <Quote className="w-5 h-5 text-fuchsia-400 flex-shrink-0 mt-0.5" />
          <div>
            <p className="text-sm text-slate-200 italic leading-relaxed">
              &quot;The biggest risk of autonomous development is not that AI won&apos;t make <span className="text-slate-400">enough</span> changes, but that it will make <span className="text-fuchsia-400 font-medium">too many</span>.&quot;
            </p>
            <div className="mt-2 flex items-center gap-2 text-[10px] text-slate-500 uppercase tracking-wider">
              <Crown className="w-3 h-3 text-fuchsia-400" />
              Constitution Article VII — Restraint Principle
            </div>
          </div>
        </div>
      </div>

      {/* ═══════════════════════════════════════════════════════
          12. Footer Stats
          ═══════════════════════════════════════════════════════ */}
      <div className="flex flex-wrap items-center gap-3 text-xs text-slate-500">
        <div className="flex items-center gap-1.5">
          <Clock className="w-3.5 h-3.5 text-fuchsia-400" />
          <span>Governor uptime: <span className="text-slate-300">247 days</span></span>
        </div>
        <span className="text-slate-700">|</span>
        <span>Last interception: <span className="text-slate-300">2 min ago</span></span>
        <span className="text-slate-700">|</span>
        <div className="flex items-center gap-1.5">
          <ShieldCheck className="w-3.5 h-3.5 text-fuchsia-400" />
          <span>Constitution version: <span className="text-fuchsia-400">1.0.0</span></span>
        </div>
        <span className="text-slate-700">|</span>
        <span>Authority score: <span className="text-fuchsia-400">100%</span></span>
        <span className="text-slate-700">|</span>
        <span>Override attempts blocked: <span className="text-slate-300">0</span></span>
      </div>

    </div>
  )
}
