import { db } from '@/lib/db'
import { NextRequest, NextResponse } from 'next/server'

// Seed content items for calendar generation
const contentItems = [
  { title: 'AI Visibility for Dentists', contentTypeId: 'blog', contentTypeLabel: 'Blog Article', gain: 6 },
  { title: 'How to Get Cited by ChatGPT', contentTypeId: 'blog', contentTypeLabel: 'Blog Article', gain: 8 },
  { title: 'Claude SEO Optimization Guide', contentTypeId: 'blog', contentTypeLabel: 'Blog Article', gain: 5 },
  { title: 'SeoSights vs Surfer SEO', contentTypeId: 'vs_page', contentTypeLabel: 'VS Page', gain: 7 },
  { title: 'AEO for SaaS', contentTypeId: 'blog', contentTypeLabel: 'Blog Article', gain: 6 },
  { title: 'Weekly AI Visibility Digest', contentTypeId: 'newsletter', contentTypeLabel: 'Newsletter', gain: 3 },
  { title: 'Gemini Citation Strategy', contentTypeId: 'blog', contentTypeLabel: 'Blog Article', gain: 5 },
  { title: 'AI Visibility for Real Estate', contentTypeId: 'blog', contentTypeLabel: 'Blog Article', gain: 4 },
  { title: 'Programmatic SEO for AI', contentTypeId: 'programmatic', contentTypeLabel: 'Programmatic Page', gain: 5 },
  { title: 'AI Score Deep Dive', contentTypeId: 'blog', contentTypeLabel: 'Blog Article', gain: 6 },
]

interface CalendarEntry {
  id: string
  title: string
  contentTypeId: string
  contentTypeLabel: string
  estimatedScoreGain: number
  briefId: string | null
  status: string
  autoGenerated: boolean
}

interface DaySchedule {
  date: string
  dayName: string
  entries: CalendarEntry[]
}

const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

function organizeByDay(
  entries: Array<{
    id: string
    date: string | Date
    title: string
    contentTypeId: string
    contentTypeLabel: string
    estimatedScoreGain: number
    briefId: string | null
    status: string
    autoGenerated: boolean
  }>,
  weekStart: Date
): DaySchedule[] {
  const result: DaySchedule[] = []

  for (let i = 0; i < 14; i++) {
    const dayDate = new Date(weekStart)
    dayDate.setDate(weekStart.getDate() + i)
    const dateStr = dayDate.toISOString().split('T')[0]
    const dayName = dayNames[dayDate.getDay()]

    const dayEntries = entries.filter(e => {
      const entryDate = new Date(e.date)
      return entryDate.toISOString().split('T')[0] === dateStr
    })

    result.push({
      date: dateStr,
      dayName,
      entries: dayEntries,
    })
  }

  return result
}

function generateSeedCalendar(weekStart: Date): DaySchedule[] {
  const result: DaySchedule[] = []
  let itemIdx = 0

  for (let i = 0; i < 14; i++) {
    const dayDate = new Date(weekStart)
    dayDate.setDate(weekStart.getDate() + i)
    const dateStr = dayDate.toISOString().split('T')[0]
    const dayName = dayNames[dayDate.getDay()]
    const isWeekend = dayDate.getDay() === 0 || dayDate.getDay() === 6

    const dayEntries: CalendarEntry[] = []

    if (!isWeekend) {
      const item = contentItems[itemIdx % contentItems.length]
      dayEntries.push({
        id: `seed-cal-${i}`,
        title: item.title,
        contentTypeId: item.contentTypeId,
        contentTypeLabel: item.contentTypeLabel,
        estimatedScoreGain: item.gain,
        briefId: null,
        status: 'scheduled',
        autoGenerated: true,
      })
      itemIdx++

      // Add second entry some days
      if (i % 3 === 0) {
        const item2 = contentItems[itemIdx % contentItems.length]
        dayEntries.push({
          id: `seed-cal-${i}-2`,
          title: item2.title,
          contentTypeId: item2.contentTypeId,
          contentTypeLabel: item2.contentTypeLabel,
          estimatedScoreGain: item2.gain,
          briefId: null,
          status: 'scheduled',
          autoGenerated: true,
        })
        itemIdx++
      }
    }

    result.push({ date: dateStr, dayName, entries: dayEntries })
  }

  return result
}

// GET /api/client-zero/content-engine/calendar
// Returns the editorial calendar for the current week + next week
export async function GET(_request: NextRequest) {
  try {
    // Calculate current week start (Monday) and next week end (Sunday)
    const now = new Date()
    const dayOfWeek = now.getDay()
    const mondayOffset = dayOfWeek === 0 ? -6 : 1 - dayOfWeek

    const weekStart = new Date(now)
    weekStart.setDate(now.getDate() + mondayOffset)
    weekStart.setHours(0, 0, 0, 0)

    const weekEnd = new Date(weekStart)
    weekEnd.setDate(weekStart.getDate() + 13)
    weekEnd.setHours(23, 59, 59, 999)

    // Query existing calendar entries
    const entries = await db.editorialCalendarEntry.findMany({
      where: {
        date: {
          gte: weekStart,
          lte: weekEnd,
        },
      },
      orderBy: { date: 'asc' },
    })

    // If entries exist, return them organized by day
    if (entries.length > 0) {
      const calendar = organizeByDay(entries, weekStart)
      return NextResponse.json({ calendar, weekStart, weekEnd })
    }

    // Auto-generate entries from Opportunity Queue if empty
    const pendingActions = await db.actionItem.findMany({
      where: {
        status: 'pending',
        domain: 'seosights.com',
      },
      orderBy: { roiScore: 'desc' },
      take: 10,
    })

    const contentTypes = [
      { id: 'blog', label: 'Blog Article' },
      { id: 'programmatic', label: 'Programmatic Page' },
      { id: 'linkedin', label: 'LinkedIn Post' },
      { id: 'vs_page', label: 'VS Page' },
      { id: 'newsletter', label: 'Newsletter' },
    ]

    const seedTopics = pendingActions.length > 0
      ? pendingActions.map(a => a.title)
      : contentItems.map(c => c.title)

    const generatedEntries: Array<{
      id: string
      date: string
      title: string
      contentTypeId: string
      contentTypeLabel: string
      estimatedScoreGain: number
      briefId: string | null
      status: string
      autoGenerated: boolean
    }> = []

    for (let i = 0; i < 14; i++) {
      const entryDate = new Date(weekStart)
      entryDate.setDate(weekStart.getDate() + i)

      // Skip weekends for blog content
      const dayNum = entryDate.getDay()
      if (dayNum === 0 || dayNum === 6) continue

      // 1-2 entries per weekday
      const numEntries = Math.random() > 0.6 ? 2 : 1
      for (let j = 0; j < numEntries; j++) {
        const topicIndex = (i + j) % seedTopics.length
        const typeIndex = (i + j) % contentTypes.length
        const ct = contentTypes[typeIndex]

        generatedEntries.push({
          id: `gen-cal-${i}-${j}`,
          date: entryDate.toISOString(),
          title: seedTopics[topicIndex],
          contentTypeId: ct.id,
          contentTypeLabel: ct.label,
          estimatedScoreGain: Math.floor(Math.random() * 6) + 3,
          briefId: null,
          status: 'scheduled',
          autoGenerated: true,
        })
      }
    }

    const calendar = organizeByDay(generatedEntries, weekStart)
    return NextResponse.json({ calendar, weekStart, weekEnd })
  } catch (error) {
    console.error('[content-engine/calendar GET] Error:', error)

    // Return seed calendar on error
    const now = new Date()
    const dayOfWeek = now.getDay()
    const mondayOffset = dayOfWeek === 0 ? -6 : 1 - dayOfWeek
    const weekStart = new Date(now)
    weekStart.setDate(now.getDate() + mondayOffset)
    weekStart.setHours(0, 0, 0, 0)
    const weekEnd = new Date(weekStart)
    weekEnd.setDate(weekStart.getDate() + 13)

    const seedCalendar = generateSeedCalendar(weekStart)
    return NextResponse.json({ calendar: seedCalendar, weekStart, weekEnd })
  }
}
