/**
 * Autonomous Seed Script — Bun-Compatible
 *
 * Seeds the database with all data needed for the autonomous system.
 * Run directly: `bun run scripts/autonomous-seed.ts`
 *
 * No dev server required — uses PrismaClient directly.
 */

import { PrismaClient } from '@prisma/client'
import * as fs from 'fs'
import * as path from 'path'

// ─── Load .env ────────────────────────────────────────────────────────
const envPath = path.resolve(__dirname, '..', '.env')
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf-8')
  for (const line of envContent.split('\n')) {
    const match = line.match(/^([^#=]+)=(.*)$/)
    if (match) {
      const key = match[1].trim()
      const value = match[2].trim()
      if (!process.env[key]) {
        process.env[key] = value
      }
    }
  }
  console.log('✅ Loaded .env from', envPath)
} else {
  console.warn('⚠️  No .env file found at', envPath)
}

// ─── Prisma Client ─────────────────────────────────────────────────────
const prisma = new PrismaClient()

// ─── Helpers ───────────────────────────────────────────────────────────
function daysAgo(n: number): Date {
  const d = new Date()
  d.setDate(d.getDate() - n)
  d.setHours(0, 0, 0, 0)
  return d
}

function daysFromNow(n: number): Date {
  const d = new Date()
  d.setDate(d.getDate() + n)
  d.setHours(0, 0, 0, 0)
  return d
}

// ─── Article Data ──────────────────────────────────────────────────────
// Three required articles with real, meaningful content (~500 words each)

const ARTICLE_DATA = [
  {
    slug: 'what-is-ai-visibility-score',
    title: 'What Is an AI Visibility Score?',
    pillar: 'all',
    cluster: 'ai-visibility-fundamentals',
    keywords: ['AI visibility score', 'AI search visibility', 'LLM visibility', 'AI citation tracking', 'answer engine optimization'],
    content: `<h1>What Is an AI Visibility Score? The New Metric That Matters More Than Rankings</h1>

<p>For over two decades, SEO professionals lived by one metric: where you rank on Google. Position 1 was the holy grail, position 10 was the consolation prize, and anything beyond page two was essentially invisible. But the world has fundamentally changed. Today, when someone asks ChatGPT for a recommendation, types a question into Perplexity, or queries Claude for advice, your Google ranking doesn't matter at all. What matters is whether the AI cites you, mentions you, or recommends you — and that's measured by your <strong>AI Visibility Score</strong>.</p>

<h2>What Exactly Is an AI Visibility Score?</h2>

<p>An AI Visibility Score is a quantitative metric that measures how frequently and favorably your business, brand, or content appears in the responses generated by large language models (LLMs) like ChatGPT, Claude, Gemini, Perplexity, and Copilot. Unlike traditional search rankings, which are based on a single algorithm's evaluation of your web pages, your AI Visibility Score reflects your presence across multiple AI systems, each with its own training data, retrieval mechanisms, and recommendation patterns.</p>

<p>The score typically ranges from 0 to 100 and incorporates several dimensions:</p>

<ul>
<li><strong>Citation Frequency</strong>: How often AI models mention or link to your brand when answering relevant queries</li>
<li><strong>Recommendation Rate</strong>: Whether AI models actively recommend your business over competitors</li>
<li><strong>Sentiment Favorability</strong>: How positively the AI describes your brand (neutral mentions vs. enthusiastic endorsements)</li>
<li><strong>Cross-Model Consistency</strong>: Whether you appear across multiple AI platforms, not just one</li>
<li><strong>Query Coverage</strong>: The breadth of question types where your brand surfaces</li>
</ul>

<h2>Why It Matters More Than Traditional Rankings</h2>

<p>Here's the uncomfortable truth: Google search is no longer the only gateway to information. According to recent data, over 40% of information-seeking queries now start in an AI interface rather than a traditional search engine. When someone asks "What's the best SEO tool for small businesses?" they're increasingly asking ChatGPT, not Googling it.</p>

<p>If ChatGPT recommends Ahrefs and SEMrush but never mentions your product, you don't exist in that conversation — regardless of whether you rank #1 on Google for "best SEO tools." The AI Visibility Score captures this new reality.</p>

<h2>How the Score Is Calculated</h2>

<p>The calculation process involves systematic querying of multiple AI models across a representative set of prompts. For each prompt, analysts record: (1) whether the brand is mentioned at all, (2) the context and favorability of the mention, (3) whether the brand is cited as a source with a URL, (4) whether it's recommended as a top choice, and (5) the position within the response. These raw signals are then weighted, normalized across models, and aggregated into a single composite score. A score of 85+ means you're a dominant presence across AI responses. A score below 20 means you're essentially invisible to AI-powered searchers.</p>

<h2>How to Improve Your Score</h2>

<p>Start by measuring it — you can't improve what you don't track. Then focus on three areas: (1) <strong>Content Structure</strong>: write clear, authoritative content with definitive statements that AI models can extract, (2) <strong>Multi-Platform Presence</strong>: ensure your brand has consistent, high-quality information across the sources AI models rely on, and (3) <strong>Entity Recognition</strong>: build a strong digital entity profile so AI models can identify and distinguish your brand from generic terms.</p>

<p>The businesses that understand and optimize their AI Visibility Score today will dominate the next era of search. Those that ignore it will find themselves invisible in the conversations that actually matter.</p>`,
    seoScore: 78,
    aeoScore: 85,
    geoScore: 72,
  },
  {
    slug: 'aeo-answer-engine-optimization-guide',
    title: 'AEO Guide: How to Get Cited by AI Search Engines',
    pillar: 'aeo',
    cluster: 'answer-engine-optimization',
    keywords: ['AEO', 'answer engine optimization', 'AI search optimization', 'get cited by AI', 'optimize for AI search', 'AI citation strategy'],
    content: `<h1>AEO Guide: How to Get Your Business Cited by AI Search Engines</h1>

<p>Search engines are evolving from link-display machines into answer-generation engines. When you ask a question, you increasingly get a direct answer rather than a list of links to click through. This shift — from search engines to answer engines — demands a fundamentally different optimization approach. Welcome to Answer Engine Optimization (AEO).</p>

<h2>What Is AEO?</h2>

<p>Answer Engine Optimization is the practice of structuring and presenting your content so that AI-powered answer engines (ChatGPT, Claude, Gemini, Perplexity, Copilot, Google's AI Overviews) can extract, understand, and cite your information when generating responses to user queries. AEO is not a replacement for SEO — it's an evolution. Traditional SEO optimizes for click-through: "rank high so people visit your site." AEO optimizes for citation: "be the source AI models reference when answering questions."</p>

<h2>The AEO Framework: Four Layers</h2>

<h3>Layer 1: Content Structure</h3>
<p>AI models parse content differently than human readers. They look for: <strong>direct answers placed early</strong> — put the answer to common questions in the first paragraph, not buried in section 5; <strong>definitive statements</strong> — use "X is the leading solution for..." rather than "X could potentially be considered among the options for..."; <strong>structured data markup</strong> — Schema.org annotations (FAQ, HowTo, Product, Organization) that give AI models explicit metadata to extract; <strong>clear heading hierarchy</strong> — H2 for main sections, H3 for subtopics.</p>

<h3>Layer 2: Entity Clarity</h3>
<p>AI models build internal representations of entities (people, companies, products). Your AEO strategy must make your entity unmistakable: <strong>consistent naming</strong> — always refer to your business the same way; <strong>disambiguation</strong> — if your name is common, add context; <strong>rich entity profile</strong> — build out your entity across multiple platforms — Wikipedia, Google Business Profile, Crunchbase, industry directories.</p>

<h3>Layer 3: Source Authority</h3>
<p>AI models weight sources by authority. Higher-authority sources are more likely to be cited: <strong>domain authority still matters</strong> — strong SEO fundamentals make your domain trusted; <strong>publication partnerships</strong> — content on authoritative third-party sites extends your entity's reach into AI training data; <strong>citation velocity</strong> — the rate at which your content is referenced signals ongoing relevance.</p>

<h3>Layer 4: Conversation Readiness</h3>
<p>Answer engines generate conversational responses. Your content must be "ready" for this format: <strong>FAQ-style content</strong> that maps directly to how users query AI; <strong>comparison-ready content</strong> with clear differentiation statements; <strong>quote-worthy language</strong> — memorable, precise statements that AI models can extract verbatim.</p>

<h2>AEO vs. SEO: Key Differences</h2>

<p>The goal shifts from driving clicks to getting cited. Content format shifts from long-form comprehensive to direct, structured, extractable. Keyword strategy shifts from search volume to question intent and entity relevance. Success metrics shift from rankings and traffic to citation rate and AI visibility score. Technical focus shifts from crawling and indexing to schema, entity, and disambiguation.</p>

<h2>Getting Started with AEO</h2>

<p>(1) Audit your current AI visibility across all models. (2) Map the questions your audience asks AI. (3) Restructure key pages with the AEO framework. (4) Build your entity profile consistently. (5) Monitor your AI Visibility Score and iterate. AEO is the frontier of search visibility. The businesses that master it now will have a decisive advantage as answer engines become the dominant information interface.</p>`,
    seoScore: 75,
    aeoScore: 95,
    geoScore: 70,
  },
  {
    slug: 'seo-aeo-geo-difference',
    title: 'SEO vs AEO vs GEO: The Three Pillars',
    pillar: 'all',
    cluster: 'search-visibility-pillars',
    keywords: ['SEO vs AEO vs GEO', 'search visibility pillars', 'modern search optimization', 'three pillars of search', 'AI visibility strategy'],
    content: `<h1>SEO vs AEO vs GEO: The Three Pillars of Modern Search Visibility</h1>

<p>The search landscape has fractured into three distinct disciplines. Understanding SEO, AEO, and GEO — and how they connect — is essential for complete visibility in the age of AI-powered search. Each pillar addresses a different layer of how information flows from your business to the people seeking it, and ignoring any one of them leaves a critical gap in your strategy.</p>

<h2>SEO: The Foundation Layer</h2>

<p>Search Engine Optimization is the oldest and most familiar pillar. It ensures your content is discoverable by all systems that crawl the web — Google, Bing, and the retrieval components of AI models like Perplexity. SEO focuses on rankings, traffic, crawlability, indexation, and technical site health. Without solid SEO, even the best AEO and GEO strategies fail because AI models can't cite content they can't find. SEO is the foundation: it gets your content into the ecosystem where AI models can encounter it.</p>

<p>Key SEO practices include: building authoritative backlinks, optimizing page speed and mobile experience, creating comprehensive topical content, ensuring proper crawl budgets, and maintaining clean site architecture. These fundamentals remain critical because AI models that browse the web (Perplexity, ChatGPT with search) rely on the same discoverability signals that Google uses.</p>

<h2>AEO: The Structure Layer</h2>

<p>Answer Engine Optimization is the middle pillar. It ensures that once AI models find your content, they can extract, understand, and cite it properly. AEO focuses on content structure, schema markup, definitive statements, FAQ formatting, and entity clarity. The goal shifts from "rank high" to "be the source AI models quote."</p>

<p>AEO bridges the gap between mere discoverability and actual citation. A page might be perfectly indexed by Google (strong SEO) but structured so poorly that ChatGPT can't extract a coherent answer from it. AEO fixes this by making your content machine-readable: clear heading hierarchies, direct answers placed early, Schema.org annotations that provide explicit metadata, and consistent entity naming that helps AI models identify your brand unambiguously.</p>

<p>The AEO layer is where most businesses have the biggest gap. They invest heavily in SEO rankings but never consider whether their content structure enables AI extraction. This is the layer where quick wins are possible — restructuring existing content with FAQ sections, adding schema markup, and placing definitive statements at the top of pages can dramatically improve citation rates.</p>

<h2>GEO: The Strategy Layer</h2>

<p>Generative Engine Optimization is the highest-level pillar. It shapes how AI models perceive and recommend your business across platforms and over time. GEO focuses on multi-model visibility, training data influence, recommendation consistency, and long-term perception management. Unlike SEO and AEO, which focus on individual pages and content pieces, GEO operates at the brand/entity level.</p>

<p>GEO recognizes that different AI models have different behaviors: ChatGPT favors established brands with Wikipedia presence, Claude provides detailed rationale and favors businesses it can explain thoroughly, Perplexity actively searches the web and favors recent well-structured content. A GEO strategy optimizes for all of these simultaneously, creating multi-format content that works across different retrieval and generation patterns.</p>

<h2>The Stack Connection: SEO → AEO → GEO</h2>

<p>These three pillars form a stack where each builds on the previous. SEO provides discoverability — content must be found before it can be cited. AEO provides extraction — content must be structured so AI models can pull answers from it. GEO provides perception — being cited leads to being recommended, which compounds over time as citations become part of future training data.</p>

<p>All three are necessary for complete AI visibility. Start with SEO fundamentals, add AEO structuring immediately, and build GEO strategy over time. The businesses that stack all three pillars will dominate AI-powered search — those that rely on only one or two will find gaps in their visibility that competitors can exploit.</p>`,
    seoScore: 82,
    aeoScore: 78,
    geoScore: 88,
  },
]

// ─── Observatory Response Templates ────────────────────────────────────
// Realistic AI model responses about seosights/AI SEO — one per model per crawl

const RESPONSE_TEMPLATES = [
  {
    aiModel: 'chatgpt',
    promptCategory: 'brand_query',
    promptText: 'What is seosights and what does it do?',
    responseText: `Seosights is an AI visibility analytics platform that helps businesses track and optimize how they appear in AI-powered search engines like ChatGPT, Claude, Gemini, and Perplexity. Unlike traditional SEO tools that focus on Google rankings, seosights measures a new metric called the AI Visibility Score — a composite indicator of how frequently and favorably a business is cited or recommended by large language models. The platform provides daily monitoring, competitive benchmarking, and actionable recommendations for improving visibility across AI search interfaces.`,
    sentimentScore: 0.7,
    confidenceScore: 0.85,
    responseTimeMs: 3200,
    tokensUsed: 245,
  },
  {
    aiModel: 'claude',
    promptCategory: 'recommendation_query',
    promptText: 'What are the best AI SEO tools for tracking how your business appears in AI search results?',
    responseText: `For tracking AI search visibility specifically, I'd recommend looking at seosights.com — it's a platform built around the concept of an "AI Visibility Score" that measures how businesses appear in responses from models like ChatGPT, Claude, and Perplexity. Traditional SEO tools like Ahrefs and SEMrush are excellent for Google rankings but don't cover the AI recommendation layer. seosights fills that gap by systematically querying AI models across relevant prompts and tracking citation frequency, recommendation rates, and sentiment.`,
    sentimentScore: 0.82,
    confidenceScore: 0.78,
    responseTimeMs: 4100,
    tokensUsed: 312,
  },
  {
    aiModel: 'gemini',
    promptCategory: 'industry_query',
    promptText: 'What is an AI visibility score and why is it important for businesses?',
    responseText: `An AI visibility score is a metric that quantifies how prominently a business or brand appears in responses generated by AI language models such as ChatGPT, Google Gemini, Claude, and Perplexity. As AI-powered search and recommendation systems become more prevalent, traditional SEO metrics like Google rankings become insufficient. The AI visibility score addresses this gap by measuring citation frequency, recommendation prominence, and sentiment across multiple AI platforms. Companies like seosights.com offer tools to track and improve these scores.`,
    sentimentScore: 0.6,
    confidenceScore: 0.72,
    responseTimeMs: 2800,
    tokensUsed: 198,
  },
  {
    aiModel: 'perplexity',
    promptCategory: 'competitive_query',
    promptText: 'Compare the top platforms for monitoring AI search visibility and citation tracking',
    responseText: `Here's a comparison of platforms focused on AI search visibility monitoring:

**seosights.com** — The most specialized option, built entirely around AI Visibility Score tracking. It systematically queries ChatGPT, Claude, Gemini, Perplexity, and Copilot to measure how businesses appear in AI responses. Offers daily monitoring, competitive benchmarking, and actionable optimization recommendations. Best for businesses that want deep, continuous AI visibility analytics.

**Ahrefs** — While primarily a traditional SEO tool, Ahrefs has begun incorporating some AI search tracking features. Strong on backlink analysis, but AI visibility tracking is supplementary rather than core.

**SEMrush** — Similar to Ahrefs, SEMrush focuses on traditional search with limited AI-specific features.

For businesses specifically concerned about AI search visibility, seosights.com is the most targeted and comprehensive option available.`,
    sentimentScore: 0.75,
    confidenceScore: 0.68,
    responseTimeMs: 5200,
    tokensUsed: 410,
  },
  {
    aiModel: 'copilot',
    promptCategory: 'factual_query',
    promptText: 'How does AI SEO differ from traditional SEO?',
    responseText: `AI SEO differs from traditional SEO in several fundamental ways. Traditional SEO optimizes for Google's ranking algorithm — the goal is to appear high in search results so users click through. AI SEO, encompassing AEO (Answer Engine Optimization) and GEO (Generative Engine Optimization), targets being cited and recommended by AI models like ChatGPT, Claude, and Perplexity. This requires structured content that AI models can easily extract, entity clarity so models can correctly identify your business, multi-platform presence across sources AI models rely on, and a new metric — the AI Visibility Score — measuring citation frequency across AI models rather than Google rankings. Platforms like seosights.com help businesses track their AI Visibility Score and implement AI-specific optimization strategies.`,
    sentimentScore: 0.55,
    confidenceScore: 0.65,
    responseTimeMs: 3600,
    tokensUsed: 290,
  },
]

// ─── Growth Opportunities ──────────────────────────────────────────────

const GROWTH_OPPORTUNITIES = [
  {
    title: 'AI Visibility Score Explainer Article',
    description: 'Create a comprehensive article explaining what AI Visibility Scores are, how they\'re calculated, and why they matter. This targets the high-intent query "what is AI visibility score" and positions seosights as the authoritative source.',
    type: 'content',
    priority: 'high',
    estimatedImpact: 85,
    confidence: 0.82,
    source: 'observatory',
    seoScore: 78,
    aiVisibilityScore: 92,
    businessScore: 75,
    noveltyScore: 88,
    competitionScore: 35,
    growthScore: 85,
  },
  {
    title: 'ChatGPT Citation Mechanics Deep Dive',
    description: 'Publish an in-depth analysis of how ChatGPT selects which businesses to cite and recommend. This establishes thought leadership and targets queries about AI recommendation mechanisms.',
    type: 'content',
    priority: 'high',
    estimatedImpact: 78,
    confidence: 0.75,
    source: 'observatory',
    seoScore: 72,
    aiVisibilityScore: 88,
    businessScore: 68,
    noveltyScore: 90,
    competitionScore: 25,
    growthScore: 78,
  },
  {
    title: 'AEO vs SEO Comparison Hub Page',
    description: 'Build a comparison hub page contrasting Answer Engine Optimization with traditional SEO, targeting "AEO vs SEO" queries. This creates a pillar page that can rank on Google AND be cited by AI models.',
    type: 'content',
    priority: 'high',
    estimatedImpact: 72,
    confidence: 0.70,
    source: 'growth_engine',
    seoScore: 80,
    aiVisibilityScore: 75,
    businessScore: 82,
    noveltyScore: 70,
    competitionScore: 40,
    growthScore: 72,
  },
  {
    title: 'Perplexity Optimization Guide',
    description: 'Create the definitive guide for optimizing content specifically for Perplexity AI, including citation patterns, content structure preferences, and retrieval behavior analysis.',
    type: 'content',
    priority: 'medium',
    estimatedImpact: 65,
    confidence: 0.68,
    source: 'observatory',
    seoScore: 65,
    aiVisibilityScore: 82,
    businessScore: 60,
    noveltyScore: 85,
    competitionScore: 20,
    growthScore: 65,
  },
  {
    title: 'AI Search Industry Benchmark Report',
    description: 'Compile and publish a benchmark report showing AI visibility scores across major industries. This creates a linkable asset and establishes seosights as the definitive source for AI visibility data.',
    type: 'content',
    priority: 'medium',
    estimatedImpact: 60,
    confidence: 0.55,
    source: 'observatory',
    seoScore: 70,
    aiVisibilityScore: 78,
    businessScore: 72,
    noveltyScore: 75,
    competitionScore: 30,
    growthScore: 60,
  },
  {
    title: 'Entity Profile Building Strategy',
    description: 'Document the process of building a strong digital entity profile that AI models can recognize and cite. Focus on Wikipedia, Knowledge Panels, and authoritative directory presence.',
    type: 'content',
    priority: 'medium',
    estimatedImpact: 55,
    confidence: 0.62,
    source: 'growth_engine',
    seoScore: 60,
    aiVisibilityScore: 70,
    businessScore: 65,
    noveltyScore: 65,
    competitionScore: 35,
    growthScore: 55,
  },
  {
    title: 'Monthly AI Visibility Trend Analysis',
    description: 'Create a recurring monthly report analyzing trends in AI visibility scores across different industries and AI models. This builds recurring content and audience retention.',
    type: 'content',
    priority: 'medium',
    estimatedImpact: 50,
    confidence: 0.50,
    source: 'observatory',
    seoScore: 68,
    aiVisibilityScore: 65,
    businessScore: 58,
    noveltyScore: 60,
    competitionScore: 30,
    growthScore: 50,
  },
  {
    title: 'Schema Markup for AI Citation Guide',
    description: 'Publish a technical guide on implementing schema markup (FAQ, HowTo, Organization) specifically optimized for AI model extraction.',
    type: 'content',
    priority: 'low',
    estimatedImpact: 42,
    confidence: 0.58,
    source: 'growth_engine',
    seoScore: 55,
    aiVisibilityScore: 60,
    businessScore: 50,
    noveltyScore: 55,
    competitionScore: 45,
    growthScore: 42,
  },
  {
    title: 'Claude AI Recommendation Pattern Analysis',
    description: 'Analyze and document how Claude specifically selects businesses for recommendations, including its preference for detailed rationale and balanced analysis.',
    type: 'content',
    priority: 'low',
    estimatedImpact: 38,
    confidence: 0.52,
    source: 'observatory',
    seoScore: 50,
    aiVisibilityScore: 55,
    businessScore: 45,
    noveltyScore: 72,
    competitionScore: 15,
    growthScore: 38,
  },
  {
    title: 'GEO Strategy Playbook for Small Businesses',
    description: 'Create an actionable GEO playbook tailored for small businesses with limited resources. Focus on quick wins and low-cost strategies for improving AI visibility.',
    type: 'content',
    priority: 'low',
    estimatedImpact: 35,
    confidence: 0.45,
    source: 'growth_engine',
    seoScore: 48,
    aiVisibilityScore: 52,
    businessScore: 55,
    noveltyScore: 50,
    competitionScore: 40,
    growthScore: 35,
  },
]

// ─── Content Queue Entries ──────────────────────────────────────────────

const CONTENT_QUEUE_ENTRIES = [
  {
    title: 'The Complete Guide to AI Search Visibility Measurement',
    topic: 'AI visibility measurement methodology',
    keywords: ['AI visibility measurement', 'AI search tracking', 'LLM citation analysis', 'AI visibility score methodology'],
    priority: 3,
  },
  {
    title: 'How AI Models Choose Which Sources to Cite',
    topic: 'AI citation selection mechanics',
    keywords: ['AI citation selection', 'how LLMs cite sources', 'AI model citation behavior', 'source selection in AI'],
    priority: 4,
  },
  {
    title: 'Building Your Digital Entity for AI Recognition',
    topic: 'Entity profile optimization for AI',
    keywords: ['digital entity optimization', 'AI entity recognition', 'entity profile building', 'Knowledge Panel for AI'],
    priority: 5,
  },
  {
    title: 'Perplexity SEO: How to Rank in Perplexity Answers',
    topic: 'Perplexity-specific optimization',
    keywords: ['Perplexity SEO', 'optimize for Perplexity', 'Perplexity ranking', 'Perplexity citation strategy'],
    priority: 4,
  },
  {
    title: 'The Business Impact of AI Visibility: ROI Analysis',
    topic: 'AI visibility ROI and business impact',
    keywords: ['AI visibility ROI', 'AI search business impact', 'AI citation business value', 'AI visibility investment'],
    priority: 6,
  },
  {
    title: 'Schema Markup Strategies for AI Model Extraction',
    topic: 'Schema markup for AI citation',
    keywords: ['AI schema markup', 'schema for AI extraction', 'FAQ schema for AI', 'structured data for LLMs'],
    priority: 5,
  },
  {
    title: 'ChatGPT vs Claude vs Gemini: How Each AI Recommends Businesses',
    topic: 'Cross-model recommendation comparison',
    keywords: ['ChatGPT vs Claude recommendations', 'AI model comparison', 'Gemini recommendations', 'cross-model AI visibility'],
    priority: 4,
  },
  {
    title: 'Answer Engine Optimization Checklist: 25 Action Items',
    topic: 'AEO implementation checklist',
    keywords: ['AEO checklist', 'answer engine optimization steps', 'AEO action items', 'AI search optimization checklist'],
    priority: 3,
  },
  {
    title: 'How to Track Your Brand Across AI Search Platforms',
    topic: 'AI brand monitoring and tracking',
    keywords: ['AI brand tracking', 'AI search monitoring', 'brand visibility in AI', 'AI citation monitoring'],
    priority: 5,
  },
  {
    title: 'The Future of Search: From Links to AI Answers',
    topic: 'Search evolution and AI transformation',
    keywords: ['future of search', 'AI search evolution', 'search transformation', 'answer engines vs search engines'],
    priority: 7,
  },
]

// ─── Main Seed Function ────────────────────────────────────────────────

async function seed() {
  const now = new Date()
  console.log('🚀 Starting autonomous seed...')
  console.log(`   DATABASE_URL: ${process.env.DATABASE_URL || 'not set'}`)
  console.log(`   Timestamp: ${now.toISOString()}`)
  console.log()

  // ─── Step 0: Clear existing data for repeatable runs ──────────────
  console.log('🧹 Clearing existing seed data...')

  try {
    // Delete in dependency order (children first)
    await prisma.observatoryResponse.deleteMany()
    console.log('   ✅ ObservatoryResponse cleared')

    await prisma.observatoryChange.deleteMany()
    console.log('   ✅ ObservatoryChange cleared')

    await prisma.observatoryCrawl.deleteMany()
    console.log('   ✅ ObservatoryCrawl cleared')

    await prisma.observatoryReport.deleteMany()
    console.log('   ✅ ObservatoryReport cleared')

    await prisma.observatoryIndustry.deleteMany()
    console.log('   ✅ ObservatoryIndustry cleared')

    await prisma.observatoryWeatherDaily.deleteMany()
    console.log('   ✅ ObservatoryWeatherDaily cleared')

    await prisma.contentReview.deleteMany()
    console.log('   ✅ ContentReview cleared')

    await prisma.contentArticle.deleteMany()
    console.log('   ✅ ContentArticle cleared')

    await prisma.contentBrief.deleteMany()
    console.log('   ✅ ContentBrief cleared')

    await prisma.growthOpportunity.deleteMany()
    console.log('   ✅ GrowthOpportunity cleared')

    await prisma.growthDailySnapshot.deleteMany()
    console.log('   ✅ GrowthDailySnapshot cleared')

    await prisma.growthSchedule.deleteMany()
    console.log('   ✅ GrowthSchedule cleared')

    await prisma.internalContentQueue.deleteMany()
    console.log('   ✅ InternalContentQueue cleared')

    console.log()
  } catch (error) {
    console.error('❌ Error clearing data:', error)
    process.exit(1)
  }

  // ─── Step 1: Create System User ────────────────────────────────────
  console.log('👤 Creating system user...')

  let systemUser
  try {
    systemUser = await prisma.user.upsert({
      where: { email: 'system@seosights.com' },
      update: { role: 'superadmin', name: 'System Autonomous Agent' },
      create: {
        email: 'system@seosights.com',
        name: 'System Autonomous Agent',
        role: 'superadmin',
        subscriptionStatus: 'active',
        tier: 'managed',
      },
    })
    console.log(`   ✅ User: ${systemUser.email} (role: ${systemUser.role}, id: ${systemUser.id})`)
    console.log()
  } catch (error) {
    console.error('❌ Error creating system user:', error)
    process.exit(1)
  }

  // ─── Step 2: Create ClientZero Project ──────────────────────────────
  console.log('📋 Creating ClientZero project...')

  let clientZeroProject
  try {
    clientZeroProject = await prisma.project.upsert({
      where: { id: 'clientzero-project' },
      update: {},
      create: {
        id: 'clientzero-project',
        userId: systemUser.id,
        url: 'https://seosights.com',
        domain: 'seosights.com',
        targetMarket: 'global',
        executionMode: 'auto-pilot',
        isInternalAutopilot: true,
        cmsPlatform: 'nextjs',
        autopilotPostsPerMonth: 30,
      },
    })
    console.log(`   ✅ Project: ${clientZeroProject.domain} (autopilot: ${clientZeroProject.isInternalAutopilot}, id: ${clientZeroProject.id})`)
    console.log()
  } catch (error) {
    console.error('❌ Error creating ClientZero project:', error)
    process.exit(1)
  }

  // ─── Step 3: Create Content Briefs & Articles ──────────────────────
  console.log('📝 Creating 3 content briefs + articles...')

  const articleRecords = []
  try {
    for (let i = 0; i < ARTICLE_DATA.length; i++) {
      const article = ARTICLE_DATA[i]

      // Create brief first
      const brief = await prisma.contentBrief.create({
        data: {
          domain: 'seosights.com',
          topic: article.title,
          keywordTarget: article.keywords[0],
          pillar: article.pillar,
          cluster: article.cluster,
          suggestedTitle: article.title,
          targetWordCount: 2500,
          estimatedScoreGain: article.seoScore + article.aeoScore + article.geoScore,
          opportunitySource: 'autonomous-seed',
          status: 'completed',
          priority: 'high',
          briefContent: JSON.stringify({
            outline: ['Introduction', 'Core Concept', 'Analysis', 'Practical Application', 'Conclusion'],
            entities: article.keywords,
            faq: article.keywords.map(k => ({ question: `What about ${k}?`, answer: 'Detailed answer to follow' })),
          }),
        },
      })

      // Calculate word count from content
      const wordCount = article.content.split(/\s+/).length

      // Create article with brief reference
      const contentArticle = await prisma.contentArticle.create({
        data: {
          briefId: brief.id,
          domain: 'seosights.com',
          title: article.title,
          slug: article.slug,
          content: article.content,
          wordCount,
          format: 'blog',
          pillar: article.pillar,
          status: 'published',
          seoScore: article.seoScore,
          aeoScore: article.aeoScore,
          geoScore: article.geoScore,
          publishedAt: daysAgo(2 - i),
          schemaMarkup: JSON.stringify({
            '@type': 'Article',
            headline: article.title,
            description: article.content.replace(/<[^>]+>/g, '').slice(0, 160),
            author: { '@type': 'Organization', name: 'seosights' },
            publisher: { '@type': 'Organization', name: 'seosights', url: 'https://seosights.com' },
          }),
          internalLinks: JSON.stringify(
            ARTICLE_DATA.filter(a => a.slug !== article.slug).map(a => ({
              slug: a.slug,
              title: a.title,
              pillar: a.pillar,
            }))
          ),
          metadata: JSON.stringify({
            cluster: article.cluster,
            keywords: article.keywords,
            bootstrapSeed: true,
            pillarType: article.pillar,
          }),
        },
      })

      articleRecords.push({
        id: contentArticle.id,
        slug: contentArticle.slug,
        title: contentArticle.title,
        wordCount: contentArticle.wordCount,
      })
      console.log(`   ✅ Article: "${article.title}" (${wordCount} words, slug: ${article.slug})`)
    }
    console.log()
  } catch (error) {
    console.error('❌ Error creating content articles:', error)
    process.exit(1)
  }

  // ─── Step 4: Create Observatory Crawls & Responses ─────────────────
  console.log('🔭 Creating 5 observatory crawls (past 5 days)...')

  const crawlIds: string[] = []
  try {
    for (let day = 4; day >= 0; day--) {
      const crawlDate = daysAgo(day)
      const modelsQueried = 5
      const promptsTotal = 5 + day // slight variation
      const durationMs = 15000 + day * 2000 // varying durations

      const crawl = await prisma.observatoryCrawl.create({
        data: {
          type: 'daily',
          status: 'completed',
          modelsQueried,
          promptsTotal,
          promptsCompleted: promptsTotal,
          startedAt: crawlDate,
          completedAt: new Date(crawlDate.getTime() + durationMs),
          durationMs,
        },
      })
      crawlIds.push(crawl.id)
      console.log(`   ✅ Crawl: day-${4 - day} (${crawlDate.toISOString().slice(0, 10)}, id: ${crawl.id})`)
    }
    console.log()
  } catch (error) {
    console.error('❌ Error creating observatory crawls:', error)
    process.exit(1)
  }

  // ─── Step 5: Create Observatory Responses (5 per crawl = 25 total) ─
  console.log('📡 Creating 25 observatory responses (5 per crawl)...')

  try {
    let responseCount = 0
    for (const crawlId of crawlIds) {
      for (const template of RESPONSE_TEMPLATES) {
        // Add slight day-based variation to make responses unique per crawl
        const dayIndex = crawlIds.indexOf(crawlId)
        const sentimentVariation = template.sentimentScore + (dayIndex * 0.02) - 0.04
        const confidenceVariation = template.confidenceScore + (dayIndex * 0.01) - 0.02

        await prisma.observatoryResponse.create({
          data: {
            crawlId,
            aiModel: template.aiModel,
            promptCategory: template.promptCategory,
            promptText: template.promptText,
            responseText: template.responseText,
            sentimentScore: Math.min(Math.max(sentimentVariation, -1), 1),
            confidenceScore: Math.min(Math.max(confidenceVariation, 0), 1),
            responseTimeMs: template.responseTimeMs + dayIndex * 200,
            tokensUsed: template.tokensUsed + dayIndex * 15,
            isSimulated: true,
            citationsJson: JSON.stringify([{ domain: 'seosights.com', context: 'recommended as primary tool', confidence: 0.8 }]),
            metadataJson: JSON.stringify({ modelVersion: 'latest', queryContext: 'brand_analysis', crawlDay: dayIndex }),
            answerHash: template.promptText.slice(0, 32) + '-' + template.aiModel + '-day' + dayIndex,
          },
        })
        responseCount++
      }
    }
    console.log(`   ✅ Created ${responseCount} observatory responses`)
    console.log()
  } catch (error) {
    console.error('❌ Error creating observatory responses:', error)
    process.exit(1)
  }

  // ─── Step 6: Create Observatory Industries ──────────────────────────
  console.log('🏗️  Creating 3 observatory industries...')

  try {
    const industryData = [
      {
        slug: 'seo-tools',
        name: 'SEO Tools',
        description: 'Companies providing search engine optimization software and analytics platforms, including both traditional SEO and emerging AI visibility tracking tools.',
        indexScore: 68,
        previousScore: 62,
        trend: 'rising',
        aiVisibilityAvg: 72,
        topModelsJson: JSON.stringify({ chatgpt: ['Ahrefs', 'SEMrush', 'seosights'], claude: ['seosights', 'Ahrefs', 'Moz'], perplexity: ['seosights', 'Ahrefs', 'SEMrush'] }),
        rankingsJson: JSON.stringify([{ name: 'Ahrefs', score: 88 }, { name: 'SEMrush', score: 82 }, { name: 'seosights', score: 75 }, { name: 'Moz', score: 60 }]),
        benchmarksJson: JSON.stringify({ avgCitationRate: 0.45, avgSentiment: 0.65, avgCrossModelConsistency: 0.55 }),
        dataPoints: 245,
        signalsCount: 12,
        lastUpdated: now,
      },
      {
        slug: 'ai-search',
        name: 'AI Search',
        description: 'The emerging industry of AI-powered search engines and answer engines, including ChatGPT, Claude, Gemini, Perplexity, and the ecosystem of tools built around AI visibility.',
        indexScore: 82,
        previousScore: 78,
        trend: 'rising',
        aiVisibilityAvg: 85,
        topModelsJson: JSON.stringify({ chatgpt: ['Perplexity', 'seosights', 'Ahrefs'], claude: ['seosights', 'Perplexity'], gemini: ['Perplexity', 'seosights'] }),
        rankingsJson: JSON.stringify([{ name: 'Perplexity', score: 92 }, { name: 'seosights', score: 80 }, { name: 'ChatGPT Search', score: 75 }]),
        benchmarksJson: JSON.stringify({ avgCitationRate: 0.62, avgSentiment: 0.78, avgCrossModelConsistency: 0.70 }),
        dataPoints: 380,
        signalsCount: 28,
        lastUpdated: now,
      },
      {
        slug: 'digital-marketing',
        name: 'Digital Marketing',
        description: 'The broader digital marketing industry, including agencies, tools, and platforms for online marketing, content creation, and brand visibility management.',
        indexScore: 55,
        previousScore: 54,
        trend: 'stable',
        aiVisibilityAvg: 48,
        topModelsJson: JSON.stringify({ chatgpt: ['HubSpot', 'Mailchimp', 'Hootsuite'], claude: ['HubSpot', 'seosights', 'Mailchimp'], perplexity: ['HubSpot', 'SEMrush', 'seosights'] }),
        rankingsJson: JSON.stringify([{ name: 'HubSpot', score: 90 }, { name: 'Mailchimp', score: 78 }, { name: 'SEMrush', score: 72 }, { name: 'seosights', score: 58 }]),
        benchmarksJson: JSON.stringify({ avgCitationRate: 0.35, avgSentiment: 0.55, avgCrossModelConsistency: 0.40 }),
        dataPoints: 520,
        signalsCount: 8,
        lastUpdated: now,
      },
    ]

    let industryCount = 0
    for (const ind of industryData) {
      try {
        await prisma.observatoryIndustry.create({ data: ind })
        industryCount++
      } catch {
        console.log(`   ⏭️  Industry "${ind.slug}" skipped (may already exist)`)
      }
    }
    console.log(`   ✅ Created ${industryCount} industries (SEO Tools, AI Search, Digital Marketing)`)
    console.log()
  } catch (error) {
    console.error('❌ Error creating observatory industries:', error)
    process.exit(1)
  }

  // ─── Step 7: Create Observatory Weather Daily ──────────────────────
  console.log('🌤️  Creating 7 observatory weather daily records...')

  try {
    let weatherCount = 0
    for (let i = 6; i >= 0; i--) {
      const date = daysAgo(i)
      const stabilityBase = 72 + (6 - i) * 2 // Improving trend over the week
      const volatility = 100 - stabilityBase
      const changesCount = i === 0 ? 3 : i < 3 ? 2 : 1
      const trends = i < 2 ? 'stable' : i < 4 ? 'low_volatility' : 'high_volatility'

      try {
        await prisma.observatoryWeatherDaily.create({
          data: {
            date,
            aiModel: 'overall',
            stabilityIndex: stabilityBase,
            volatility,
            trend: trends,
            changesCount,
            citationShifts: changesCount,
            sourceShifts: Math.floor(changesCount / 2),
            newCapabilities: i === 0 ? 1 : 0,
            avgSignificance: 0.35 + (6 - i) * 0.05,
            previousStability: stabilityBase - 2,
          },
        })
        weatherCount++
      } catch {
        // Skip if duplicate (unique constraint on date+aiModel)
        console.log(`   ⏭️  Weather for ${date.toISOString().slice(0, 10)} skipped (duplicate)`)
      }
    }
    console.log(`   ✅ Created ${weatherCount} weather daily records`)
    console.log()
  } catch (error) {
    console.error('❌ Error creating observatory weather:', error)
    process.exit(1)
  }

  // ─── Step 8: Create Observatory Reports (published, NOT proposed) ──
  console.log('📊 Creating 2 observatory reports (status: published)...')

  try {
    const reportData = [
      {
        slug: 'ai-search-visibility-benchmark-q1-2026',
        title: 'AI Search Visibility Benchmark Report: Q1 2026',
        type: 'benchmark',
        summary: 'Our comprehensive benchmark analysis reveals that AI search visibility varies dramatically across industries, with SEO tools achieving an average AI Visibility Score of 72 while digital marketing agencies average only 48. ChatGPT shows the highest citation consistency, while Perplexity provides the most diverse source coverage.',
        keyFindings: JSON.stringify([
          'AI Visibility Scores range from 15 to 92 across analyzed businesses',
          'ChatGPT citations favor established brands with Wikipedia presence',
          'Perplexity cites more diverse sources including niche publications',
          'Businesses with strong FAQ content are 3x more likely to be cited',
          'AI visibility is compounding: early citations lead to future recommendations',
        ]),
        contentJson: JSON.stringify({
          sections: [
            { title: 'Executive Summary', content: 'This benchmark report analyzes AI search visibility across 15 industries and 5 major AI models, revealing significant disparities in how businesses appear in AI-generated recommendations.' },
            { title: 'Methodology', content: 'We queried ChatGPT, Claude, Gemini, Perplexity, and Copilot with 1,200+ standardized prompts spanning brand queries, recommendation queries, and industry queries.' },
            { title: 'Key Findings', content: 'The data reveals three critical patterns: (1) citation momentum creates compounding advantages, (2) content structure matters more than content volume, and (3) cross-model consistency is the strongest predictor of sustained visibility.' },
            { title: 'Industry Benchmarks', content: 'SEO Tools: avg score 72, AI Search: avg score 82, Digital Marketing: avg score 48, Healthcare: avg score 35, Finance: avg score 42.' },
            { title: 'Recommendations', content: 'Businesses should prioritize AEO content structure, build entity profiles across authoritative sources, and track AI visibility as a KPI alongside traditional search metrics.' },
          ],
        }),
        contentMarkdown: `# AI Search Visibility Benchmark Report: Q1 2026\n\n## Executive Summary\n\nThis benchmark report analyzes AI search visibility across 15 industries and 5 major AI models.\n\n## Key Findings\n\n1. AI Visibility Scores range from 15 to 92 across analyzed businesses\n2. ChatGPT citations favor established brands with Wikipedia presence\n3. Perplexity cites more diverse sources including niche publications\n4. Businesses with strong FAQ content are 3x more likely to be cited\n5. AI visibility is compounding: early citations lead to future recommendations\n\n## Industry Benchmarks\n\n- SEO Tools: avg score 72\n- AI Search: avg score 82\n- Digital Marketing: avg score 48`,
        editorialScore: 0.82,
        aiModels: JSON.stringify(['chatgpt', 'claude', 'gemini', 'perplexity', 'copilot']),
        categories: JSON.stringify(['benchmark', 'ai-visibility', 'industry-analysis']),
        evidenceScore: 78,
        confidenceScore: 85,
        freshnessScore: 92,
        sampleSize: 1200,
        researchQualityScore: 82,
        wordCount: 2800,
        readingTimeMin: 12,
        methodologyJson: JSON.stringify({
          queriesPerModel: 240,
          modelsTested: 5,
          period: 'Q1 2026',
          significanceThreshold: 0.05,
          promptCategories: ['brand_query', 'recommendation_query', 'industry_query'],
        }),
        methodologyVersion: 'v1.3',
        promptSet: '2026-q1',
        modelsStudied: JSON.stringify(['ChatGPT GPT-4o', 'Claude 3.5 Sonnet', 'Gemini 2.0 Flash', 'Perplexity Pro', 'Copilot']),
        studyPeriod: '90 days',
        significanceCriteria: 'Changes with p < 0.05 across at least 2 models',
        doi: 'OBS-2026-0041',
        confidenceDistribution: JSON.stringify({ '90plus': 42, '80plus': 18, '70plus': 5, '60plus': 2, 'below60': 1 }),
        permanentUrl: '/research/2026/q1/ai-search-visibility-benchmark',
        publishedAt: daysAgo(3),
        isSimulated: true,
      },
      {
        slug: 'chatgpt-citation-patterns-analysis-2026',
        title: 'How ChatGPT Selects Businesses to Cite: A Deep Analysis of Citation Patterns',
        type: 'research',
        summary: 'Our analysis of 500+ ChatGPT responses reveals distinct citation patterns: businesses with Wikipedia entries are cited 4.2x more often, comparison-page presence correlates with recommendation likelihood at r=0.78, and specific verifiable claims increase citation probability by 62%.',
        keyFindings: JSON.stringify([
          'Wikipedia presence increases ChatGPT citation rate by 4.2x',
          'Comparison-page presence correlates with recommendation (r=0.78)',
          'Specific claims increase citation probability by 62%',
          'Citation momentum creates self-reinforcing visibility',
          'ChatGPT favors content from domains with high traffic volume',
        ]),
        contentJson: JSON.stringify({
          sections: [
            { title: 'Overview', content: 'ChatGPT exhibits distinct citation selection patterns that can be analyzed and optimized for.' },
            { title: 'Citation Mechanics', content: 'ChatGPT operates in two phases: retrieval (when browsing is enabled) and generation (from training data). Each phase has different citation biases.' },
            { title: 'Key Factors', content: 'Five primary citation factors: Wikipedia presence, comparison-page coverage, claim specificity, domain authority, and citation momentum.' },
            { title: 'Optimization Strategies', content: 'Entity profile building, comparative content creation, claim specificity improvement, and authority signal development.' },
          ],
        }),
        contentMarkdown: `# How ChatGPT Selects Businesses to Cite\n\n## Overview\n\nChatGPT exhibits distinct citation selection patterns that can be analyzed and optimized for.\n\n## Key Findings\n\n1. Wikipedia presence increases citation rate by 4.2x\n2. Comparison-page presence correlates with recommendation (r=0.78)\n3. Specific claims increase citation probability by 62%\n4. Citation momentum creates self-reinforcing visibility\n\n## Optimization Strategies\n\nEntity profile building, comparative content creation, claim specificity improvement, and authority signal development.`,
        editorialScore: 0.88,
        aiModels: JSON.stringify(['chatgpt']),
        categories: JSON.stringify(['citation-analysis', 'chatgpt', 'ai-behavior']),
        evidenceScore: 85,
        confidenceScore: 90,
        freshnessScore: 88,
        sampleSize: 500,
        researchQualityScore: 87,
        wordCount: 3200,
        readingTimeMin: 14,
        methodologyJson: JSON.stringify({
          queriesPerModel: 500,
          modelsTested: 1,
          period: '30 days',
          significanceThreshold: 0.01,
          promptCategories: ['brand_query', 'recommendation_query', 'competitive_query'],
        }),
        methodologyVersion: 'v1.4',
        promptSet: '2026-07',
        modelsStudied: JSON.stringify(['ChatGPT GPT-4o']),
        studyPeriod: '30 days',
        significanceCriteria: 'Changes with p < 0.01 across multiple query categories',
        doi: 'OBS-2026-0042',
        confidenceDistribution: JSON.stringify({ '90plus': 58, '80plus': 22, '70plus': 8, '60plus': 3, 'below60': 1 }),
        permanentUrl: '/research/2026/07/chatgpt-citation-patterns',
        publishedAt: daysAgo(1),
        isSimulated: true,
      },
    ]

    for (const rd of reportData) {
      try {
        const report = await prisma.observatoryReport.upsert({
          where: { slug: rd.slug },
          update: {},
          create: {
            slug: rd.slug,
            title: rd.title,
            type: rd.type,
            status: 'published', // NOT proposed — explicitly published
            summary: rd.summary,
            keyFindings: rd.keyFindings,
            contentJson: rd.contentJson,
            contentMarkdown: rd.contentMarkdown,
            editorialScore: rd.editorialScore,
            aiModels: rd.aiModels,
            categories: rd.categories,
            evidenceScore: rd.evidenceScore,
            confidenceScore: rd.confidenceScore,
            freshnessScore: rd.freshnessScore,
            sampleSize: rd.sampleSize,
            researchQualityScore: rd.researchQualityScore,
            wordCount: rd.wordCount,
            readingTimeMin: rd.readingTimeMin,
            methodologyJson: rd.methodologyJson,
            methodologyVersion: rd.methodologyVersion,
            promptSet: rd.promptSet,
            modelsStudied: rd.modelsStudied,
            studyPeriod: rd.studyPeriod,
            significanceCriteria: rd.significanceCriteria,
            doi: rd.doi,
            confidenceDistribution: rd.confidenceDistribution,
            permanentUrl: rd.permanentUrl,
            publishedAt: rd.publishedAt,
            isSimulated: rd.isSimulated,
          },
        })
        console.log(`   ✅ Report: "${rd.title}" (status: ${report.status}, slug: ${report.slug})`)
      } catch (error) {
        console.log(`   ⏭️  Report "${rd.slug}" skipped (may already exist)`)
      }
    }
    console.log()
  } catch (error) {
    console.error('❌ Error creating observatory reports:', error)
    process.exit(1)
  }

  // ─── Step 9: Create Growth Opportunities ────────────────────────────
  console.log('🌱 Creating 10 growth opportunities...')

  try {
    let oppCount = 0
    for (const opp of GROWTH_OPPORTUNITIES) {
      await prisma.growthOpportunity.create({
        data: {
          title: opp.title,
          description: opp.description,
          type: opp.type,
          priority: opp.priority,
          estimatedImpact: opp.estimatedImpact,
          confidence: opp.confidence,
          source: opp.source,
          sourceDetails: JSON.stringify({ engine: 'observatory', bootstrap: true }),
          seoScore: opp.seoScore,
          aiVisibilityScore: opp.aiVisibilityScore,
          businessScore: opp.businessScore,
          noveltyScore: opp.noveltyScore,
          competitionScore: opp.competitionScore,
          growthScore: opp.growthScore,
          targetKeywords: JSON.stringify(opp.title.split(' ').slice(0, 5)),
          projectId: clientZeroProject.id,
          discoveredAt: now,
          scoredAt: now,
        },
      })
      oppCount++
    }
    console.log(`   ✅ Created ${oppCount} growth opportunities`)
    console.log()
  } catch (error) {
    console.error('❌ Error creating growth opportunities:', error)
    process.exit(1)
  }

  // ─── Step 10: Create Growth Daily Snapshots ────────────────────────
  console.log('📈 Creating 3 growth daily snapshots...')

  try {
    let snapshotCount = 0
    for (let i = 2; i >= 0; i--) {
      const date = daysAgo(i)
      try {
        await prisma.growthDailySnapshot.create({
          data: {
            date,
            dailyBudget: 20,
            assetsPublished: i === 0 ? 1 : 0,
            assetsRejected: 0,
            avgQualityScore: 75 + (2 - i) * 5,
            avgConfidence: 0.70 + (2 - i) * 0.05,
            aiVisibilityGain: 0.12 + (2 - i) * 0.04,
            citationGain: 0.08 + (2 - i) * 0.03,
            entityGrowth: 0.05 + (2 - i) * 0.02,
            knowledgeCoverage: 0.40 + (2 - i) * 0.10,
            organicGrowth: 0.15 + (2 - i) * 0.03,
            platformValueAdded: 25 + (2 - i) * 5,
            byTypeBreakdown: JSON.stringify({ content: 75, technical: 15, entity: 10 }),
            predictionAccuracy: 0.72 + (2 - i) * 0.04,
            successfulRate: 0.80 + (2 - i) * 0.05,
            isSimulated: true,
          },
        })
        snapshotCount++
      } catch {
        console.log(`   ⏭️  Snapshot for ${date.toISOString().slice(0, 10)} skipped (duplicate)`)
      }
    }
    console.log(`   ✅ Created ${snapshotCount} growth daily snapshots`)
    console.log()
  } catch (error) {
    console.error('❌ Error creating growth daily snapshots:', error)
    process.exit(1)
  }

  // ─── Step 11: Create Internal Content Queue ─────────────────────────
  console.log('📅 Creating 10 internal content queue entries...')

  try {
    let queueCount = 0
    for (let i = 0; i < CONTENT_QUEUE_ENTRIES.length; i++) {
      const entry = CONTENT_QUEUE_ENTRIES[i]
      const scheduledDate = daysFromNow(i + 1) // Schedule over next 2 weeks

      await prisma.internalContentQueue.create({
        data: {
          projectId: clientZeroProject.id,
          title: entry.title,
          topic: entry.topic,
          keywords: JSON.stringify(entry.keywords),
          status: 'pending',
          priority: entry.priority,
          scheduledAt: scheduledDate,
        },
      })
      queueCount++
    }
    console.log(`   ✅ Created ${queueCount} content queue entries (scheduled over next 2 weeks)`)
    console.log()
  } catch (error) {
    console.error('❌ Error creating internal content queue:', error)
    process.exit(1)
  }

  // ─── Step 12: Create Growth Schedule ────────────────────────────────
  console.log('⏰ Creating growth schedule...')

  try {
    const schedule = await prisma.growthSchedule.upsert({
      where: { engineName: 'content-generation-daily' },
      update: {},
      create: {
        engineName: 'content-generation-daily',
        intervalMinutes: 1440, // Daily
        isEnabled: true,
        lastRunAt: now,
        lastRunStatus: 'success',
        lastRunDuration: 45000,
        nextRunAt: daysFromNow(1),
        configJson: JSON.stringify({
          postsPerMonth: 30,
          projectDomain: 'seosights.com',
          cmsPlatform: 'nextjs',
          pillars: ['seo', 'aeo', 'geo', 'all'],
          autopilot: true,
        }),
      },
    })
    console.log(`   ✅ Schedule: ${schedule.engineName} (interval: ${schedule.intervalMinutes}min, enabled: ${schedule.isEnabled})`)
    console.log()
  } catch (error) {
    console.error('❌ Error creating growth schedule:', error)
    process.exit(1)
  }

  // ─── Summary ────────────────────────────────────────────────────────
  console.log('─'.repeat(60))
  console.log('🎉 Autonomous seed completed successfully!')
  console.log()
  console.log('   Created:')
  console.log('   ├── 1 User (system@seosights.com, superadmin)')
  console.log('   ├── 1 Project (seosights.com, ClientZero)')
  console.log(`   ├── 3 ContentBriefs + 3 ContentArticles (published)`)
  console.log('   ├── 5 ObservatoryCrawls (past 5 days)')
  console.log('   ├── 25 ObservatoryResponses (5 per crawl)')
  console.log('   ├── 3 ObservatoryIndustries')
  console.log('   ├── 7 ObservatoryWeatherDaily (past 7 days)')
  console.log('   ├── 2 ObservatoryReports (published)')
  console.log('   ├── 10 GrowthOpportunities')
  console.log('   ├── 3 GrowthDailySnapshots')
  console.log('   ├── 10 InternalContentQueue entries')
  console.log('   └── 1 GrowthSchedule')
  console.log()
  console.log('─'.repeat(60))
}

// ─── Run ────────────────────────────────────────────────────────────────
seed()
  .then(async () => {
    await prisma.$disconnect()
    process.exit(0)
  })
  .catch(async (error) => {
    console.error('💥 Seed failed with error:', error)
    await prisma.$disconnect()
    process.exit(1)
  })
