/**
 * Cron API — Autonomous Bootstrap
 *
 * GET /api/cron/autonomous-bootstrap
 *
 * Purpose: Seed the entire system with all necessary data for autonomous operation.
 * Creates ClientZero project, observatory data, growth engine data, content articles,
 * content queue entries, token usage tracking, and a superadmin system user.
 *
 * This is the KEY endpoint that makes the entire seosights.com system work autonomously.
 * Called once (or as needed) to bootstrap the full self-referential marketing engine.
 */

import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'

export const dynamic = 'force-dynamic'

// ─── Authorization ──────────────────────────────────────────────────

function isAuthorized(request: NextRequest): boolean {
  const secret = process.env.CRON_SECRET
  if (!secret) return true // No secret → dev/sandbox mode

  const authHeader = request.headers.get('authorization') || ''
  const bearerMatch = authHeader.match(/^Bearer\s+(.+)$/i)
  if (bearerMatch && bearerMatch[1] === secret) return true

  const xHeader = request.headers.get('x-cron-secret')
  if (xHeader && xHeader === secret) return true

  // Vercel Cron Jobs send this header automatically
  const vercelHeader = request.headers.get('x-vercel-cron-secret')
  if (vercelHeader && vercelHeader === secret) return true

  return false
}

// ─── Helper: date offset ────────────────────────────────────────────

function daysAgo(n: number): Date {
  const d = new Date()
  d.setDate(d.getDate() - n)
  d.setHours(0, 0, 0, 0)
  return d
}

function daysFromNow(n: number): Date {
  const d = new Date()
  d.setDate(d.getDate() + n)
  d.setHours(0, 0, 0, 0)
  return d
}

// ─── Article Content ────────────────────────────────────────────────
// Real, meaningful content for each article topic — 500+ words each

const ARTICLE_DATA = [
  {
    slug: 'what-is-ai-visibility-score',
    title: 'What Is an AI Visibility Score? The New Metric That Matters More Than Rankings',
    pillar: 'all',
    cluster: 'ai-visibility-fundamentals',
    keywords: ['AI visibility score', 'AI search visibility', 'LLM visibility', 'AI citation tracking', 'answer engine optimization'],
    content: `# What Is an AI Visibility Score? The New Metric That Matters More Than Rankings

For over two decades, SEO professionals lived by one metric: where you rank on Google. Position 1 was the holy grail, position 10 was the consolation prize, and anything beyond page two was essentially invisible. But the world has fundamentally changed. Today, when someone asks ChatGPT for a recommendation, types a question into Perplexity, or queries Claude for advice, your Google ranking doesn't matter at all. What matters is whether the AI cites you, mentions you, or recommends you — and that's measured by your **AI Visibility Score**.

## What Exactly Is an AI Visibility Score?

An AI Visibility Score is a quantitative metric that measures how frequently and favorably your business, brand, or content appears in the responses generated by large language models (LLMs) like ChatGPT, Claude, Gemini, Perplexity, and Copilot. Unlike traditional search rankings, which are based on a single algorithm's evaluation of your web pages, your AI Visibility Score reflects your presence across multiple AI systems, each with its own training data, retrieval mechanisms, and recommendation patterns.

The score typically ranges from 0 to 100 and incorporates several dimensions:

- **Citation Frequency**: How often AI models mention or link to your brand when answering relevant queries
- **Recommendation Rate**: Whether AI models actively recommend your business over competitors
- **Sentiment Favorability**: How positively the AI describes your brand (neutral mentions vs. enthusiastic endorsements)
- **Cross-Model Consistency**: Whether you appear across multiple AI platforms, not just one
- **Query Coverage**: The breadth of question types where your brand surfaces

## Why It Matters More Than Traditional Rankings

Here's the uncomfortable truth: Google search is no longer the only gateway to information. According to recent data, over 40% of information-seeking queries now start in an AI interface rather than a traditional search engine. When someone asks "What's the best SEO tool for small businesses?" they're increasingly asking ChatGPT, not Googling it.

If ChatGPT recommends Ahrefs and SEMrush but never mentions your product, you don't exist in that conversation — regardless of whether you rank #1 on Google for "best SEO tools." The AI Visibility Score captures this new reality.

## How the Score Is Calculated

The calculation process involves systematic querying of multiple AI models across a representative set of prompts. For each prompt, analysts record:

1. Whether the brand is mentioned at all
2. The context and favorability of the mention
3. Whether the brand is cited as a source (with a URL)
4. Whether it's recommended as a top choice
5. The position within the response (first mention vs. buried at the end)

These raw signals are then weighted, normalized across models, and aggregated into a single composite score. A score of 85+ means you're a dominant presence across AI responses. A score below 20 means you're essentially invisible to AI-powered searchers.

## The Three Pillars: SEO, AEO, and GEO

Your AI Visibility Score connects directly to three optimization pillars:

- **SEO** (Search Engine Optimization): Still matters as a foundation — AI models crawl the web
- **AEO** (Answer Engine Optimization): Structuring content so AI models can extract and cite it
- **GEO** (Generative Engine Optimization): Actively shaping how generative AI systems perceive and recommend you

The AI Visibility Score is the unified outcome metric that ties all three together. Improving any pillar should move your score upward.

## How to Improve Your Score

Start by measuring it — you can't improve what you don't track. Then focus on three areas:

1. **Content Structure**: Write clear, authoritative content with definitive statements that AI models can extract
2. **Multi-Platform Presence**: Ensure your brand has consistent, high-quality information across the sources AI models rely on (Wikipedia, industry directories, review platforms)
3. **Entity Recognition**: Build a strong digital entity profile so AI models can identify and distinguish your brand from generic terms

The businesses that understand and optimize their AI Visibility Score today will dominate the next era of search. Those that ignore it will find themselves invisible in the conversations that actually matter.`,
    seoScore: 78,
    aeoScore: 85,
    geoScore: 72,
  },
  {
    slug: 'how-chatgpt-recommends-businesses',
    title: 'How ChatGPT Recommends Businesses: Inside the AI Citation Engine',
    pillar: 'aeo',
    cluster: 'ai-model-behavior',
    keywords: ['ChatGPT recommendations', 'AI citation engine', 'how LLMs recommend businesses', 'ChatGPT business citations', 'AI search mechanics'],
    content: `# How ChatGPT Recommends Businesses: Inside the AI Citation Engine

When you ask ChatGPT "What's the best CRM for a small startup?" and it responds with a thoughtful comparison mentioning HubSpot, Pipedrive, and Zoho — how did it choose those three? What mechanism determines which businesses get cited and which get ignored? Understanding this process is critical for any business that wants to appear in AI-generated recommendations.

## The Two-Phase Recommendation Process

ChatGPT's recommendation process operates in two distinct phases, each with different implications for visibility:

**Phase 1: Retrieval** — When ChatGPT has browsing enabled, it actively searches the web for relevant content. This phase behaves somewhat like a search engine, looking for authoritative, recent, and well-structured content about the topic. The retrieval phase favors content that is clearly organized, uses definitive language, and comes from sources with established credibility.

**Phase 2: Generation** — Even without browsing, ChatGPT draws from its training data to formulate responses. This phase is more like a knowledge extraction process, where the model pulls from the vast corpus of internet content it absorbed during training. Here, businesses that were frequently discussed, widely reviewed, and consistently associated with specific categories in the training data have a natural advantage.

## What Makes a Business "Citable"?

Through extensive analysis of ChatGPT responses across thousands of queries, several patterns emerge in what makes a business citable:

### 1. Category Anchoring
ChatGPT associates businesses with specific categories. If your business is strongly associated with "project management software" in online discourse — through reviews, comparisons, category pages, and industry discussions — ChatGPT is more likely to retrieve you when that category is queried. Weak or ambiguous category associations mean you'll be overlooked.

### 2. Authority Signals
The model looks for authority indicators: mentions in authoritative publications, Wikipedia entries, strong review profiles, and consistent presence across multiple high-quality sources. A business mentioned only on its own website and a few low-quality directories has minimal authority from ChatGPT's perspective.

### 3. Comparative Context
ChatGPT loves comparisons. When it recommends businesses, it typically provides a comparison — "X is best for beginners, Y is better for enterprise." Businesses that appear frequently in comparison content (vs. pages, "top 10" lists, competitor analyses) are more likely to be surfaced.

### 4. Specificity of Claims
Vague, marketing-heavy content is less citable. ChatGPT favors content that makes specific, verifiable claims: "handles up to 10,000 concurrent users," "integrates with 200+ apps," "reduces deployment time by 60%." These concrete details give the model something to extract and relay to users.

## The Citation Bias Problem

There's a significant bias in how ChatGPT recommends businesses: it tends to favor established, well-known brands over newer or smaller ones, regardless of actual quality. This "citation rich get richer" effect means that early visibility creates a compounding advantage — the more ChatGPT cites you, the more future conversations reinforce that citation pattern.

This is precisely why proactive AI visibility optimization matters. Without deliberate effort, newer or smaller businesses will remain invisible in AI responses simply because they haven't yet built the citation momentum that ChatGPT's generation process favors.

## Practical Strategies to Get Cited

Based on how the citation engine works, here are concrete strategies:

1. **Create definitive category content**: Publish authoritative guides that firmly position your business within a specific category
2. **Build comparison pages**: Create honest, detailed comparisons between your product and competitors
3. **Earn authoritative mentions**: Get coverage in publications that ChatGPT's training data likely includes
4. **Use specific, verifiable claims**: Replace marketing speak with concrete, data-backed statements
5. **Maintain consistent entity data**: Ensure your business information is consistent across Wikipedia, Google Knowledge Panel, review sites, and industry directories

The businesses that understand ChatGPT's citation mechanics and optimize for them will find themselves in the AI's recommended list — and that visibility compounds over time.`,
    seoScore: 82,
    aeoScore: 90,
    geoScore: 75,
  },
  {
    slug: 'aeo-answer-engine-optimization-guide',
    title: 'AEO Guide: How to Get Your Business Cited by AI Search Engines',
    pillar: 'aeo',
    cluster: 'answer-engine-optimization',
    keywords: ['AEO', 'answer engine optimization', 'AI search optimization', 'get cited by AI', 'optimize for AI search', 'AI citation strategy'],
    content: `# AEO Guide: How to Get Your Business Cited by AI Search Engines

Search engines are evolving from link-display machines into answer-generation engines. When you ask a question, you increasingly get a direct answer rather than a list of links to click through. This shift — from search engines to answer engines — demands a fundamentally different optimization approach. Welcome to Answer Engine Optimization (AEO).

## What Is AEO?

Answer Engine Optimization is the practice of structuring and presenting your content so that AI-powered answer engines (ChatGPT, Claude, Gemini, Perplexity, Copilot, Google's AI Overviews) can extract, understand, and cite your information when generating responses to user queries.

AEO is not a replacement for SEO — it's an evolution. Traditional SEO optimizes for click-through: "rank high so people visit your site." AEO optimizes for citation: "be the source AI models reference when answering questions." The end goal shifts from traffic to authority and visibility in AI-generated answers.

## The AEO Framework: Four Layers

### Layer 1: Content Structure

AI models parse content differently than human readers. They look for:

- **Direct answers placed early**: Put the answer to common questions in the first paragraph, not buried in section 5
- **Definitive statements**: Use "X is the leading solution for..." rather than "X could potentially be considered among the options for..."
- **Structured data markup**: Schema.org annotations (FAQ, HowTo, Product, Organization) that give AI models explicit metadata to extract
- **Clear heading hierarchy**: H2 for main sections, H3 for subtopics — models use heading structure to navigate content

### Layer 2: Entity Clarity

AI models build internal representations of entities (people, companies, products). Your AEO strategy must make your entity unmistakable:

- **Consistent naming**: Always refer to your business the same way — don't alternate between "Acme Corp," "Acme," and "Acme Corporation"
- **Disambiguation**: If your name is common, add context: "Acme Corp (project management software)" not just "Acme"
- **Rich entity profile**: Build out your entity across multiple platforms — Wikipedia, Google Business Profile, Crunchbase, industry directories

### Layer 3: Source Authority

AI models weight sources by authority. Higher-authority sources are more likely to be cited:

- **Domain authority still matters**: Strong SEO fundamentals (backlinks, content quality, site reputation) make your domain a trusted source
- **Publication partnerships**: Content published on authoritative third-party sites (industry publications, major media) extends your entity's reach into the AI's training corpus
- **Citation velocity**: The rate at which your content is referenced by other sources signals ongoing relevance

### Layer 4: Conversation Readiness

Answer engines don't just retrieve documents — they generate conversational responses. Your content must be "ready" for this format:

- **FAQ-style content**: Questions and answers that map directly to how users query AI
- **Comparison-ready content**: Clear statements about how your offering differs from alternatives
- **Quote-worthy language**: Memorable, precise statements that AI models can extract verbatim

## AEO vs. SEO: Key Differences

| Dimension | SEO | AEO |
|-----------|-----|-----|
| Goal | Drive clicks to your site | Get cited in AI responses |
| Content format | Long-form, comprehensive | Direct, structured, extractable |
| Keyword strategy | Search volume + competition | Question intent + entity relevance |
| Success metric | Rankings + traffic | Citation rate + AI visibility score |
| Technical focus | Crawling + indexing | Schema + entity + disambiguation |

## Getting Started with AEO

1. **Audit your current AI visibility**: Run systematic queries across ChatGPT, Claude, and Perplexity to see if your business appears
2. **Map the questions your audience asks AI**: Document the exact prompts people use when seeking your type of service
3. **Restructure your key pages**: Apply the AEO framework to your most important content
4. **Build your entity profile**: Ensure consistent, comprehensive representation across authoritative platforms
5. **Monitor and iterate**: Track your AI Visibility Score over time and refine your approach

AEO is the frontier of search visibility. The businesses that master it now will have a decisive advantage as answer engines become the dominant information interface.`,
    seoScore: 75,
    aeoScore: 95,
    geoScore: 70,
  },
  {
    slug: 'geo-generative-engine-optimization',
    title: 'GEO Explained: Optimizing for Perplexity, Claude, and AI Overviews',
    pillar: 'geo',
    cluster: 'generative-engine-optimization',
    keywords: ['GEO', 'generative engine optimization', 'optimize for Perplexity', 'Claude optimization', 'AI Overviews', 'GEO strategy'],
    content: `# GEO Explained: Optimizing for Perplexity, Claude, and AI Overviews

Generative Engine Optimization (GEO) is the practice of actively shaping how generative AI systems perceive, represent, and recommend your business. While AEO focuses on content structure and SEO focuses on rankings, GEO operates at a higher level — it's about influencing the AI's understanding of your entity in the broader knowledge landscape.

## Why GEO Is Different

Traditional SEO assumes a relatively simple pipeline: you optimize content → Google crawls it → Google ranks it → users find it. GEO operates in a far more complex ecosystem:

- **Multiple models, multiple behaviors**: ChatGPT, Claude, Gemini, Perplexity, and Copilot each have different retrieval mechanisms, training data biases, and recommendation patterns
- **Dynamic responses**: The same query can produce different recommendations over time as models update, learn, and evolve
- **Compound citations**: AI models don't just rank — they synthesize, compare, and narrate, meaning your visibility depends on how you fit into a broader story
- **Training data persistence**: What AI models learned about you during training persists even if you change your website today

GEO addresses this complexity by taking a strategic, multi-model approach to visibility.

## The Three Pillars of GEO

### 1. Perplexity Optimization

Perplexity is a retrieval-first answer engine. It actively searches the web when responding to queries, which means:

- **Real-time content matters**: Perplexity crawls current web content, so recent updates can immediately affect your visibility
- **Source diversity**: Perplexity cites multiple sources per answer, so appearing on many authoritative sites increases your citation odds
- **Structured responses**: Perplexity organizes answers into sections with citations, so content with clear structure and definitive claims is favored
- **Academic and technical depth**: Perplexity tends to favor sources with deep, well-researched content over superficial marketing pages

**GEO tactics for Perplexity**: Publish comprehensive, well-structured content with clear citations of your own sources. Maintain active presence on multiple authoritative platforms.

### 2. Claude Optimization

Claude (by Anthropic) tends to be more conversational and nuanced in its recommendations:

- **Contextual reasoning**: Claude often provides more detailed rationale for recommendations, favoring businesses it can explain thoroughly
- **Balanced analysis**: Claude tends to present multiple options with pros/cons, so businesses with clear positioning statements benefit
- **Training data focus**: Claude's training emphasizes diverse, high-quality sources — academic papers, detailed reviews, and substantive blog content carry more weight

**GEO tactics for Claude**: Create in-depth content that explains your positioning clearly. Build presence in sources Claude's training likely emphasizes — detailed reviews, technical documentation, and thoughtful analysis pieces.

### 3. AI Overviews (Google)

Google's AI Overviews synthesize information from multiple web sources into a generated answer at the top of search results:

- **Search-visible sources**: AI Overviews pull from content that Google already indexes and ranks well
- **E-E-A-T emphasis**: Experience, Expertise, Authority, and Trustworthiness — the same signals that drive Google rankings also drive AI Overview citations
- **Freshness**: AI Overviews tend to cite recent, relevant content for current-events and evolving-topic queries

**GEO tactics for AI Overviews**: Combine strong SEO fundamentals with AEO content structure. Ensure your most authoritative pages are optimized for both traditional ranking and AI citation extraction.

## GEO Strategy: The Multi-Model Approach

The core GEO insight is that you must optimize for multiple models simultaneously. A strategy that works for Perplexity (retrieval-focused) may differ from what works for Claude (training-data-focused). The unified GEO approach:

1. **Measure per-model visibility**: Track your citation rates across ChatGPT, Claude, Gemini, Perplexity, and Copilot individually
2. **Identify model-specific gaps**: If Claude cites you but Perplexity doesn't, diagnose why — different retrieval patterns, different training biases
3. **Create multi-format content**: Same information, different formats — detailed guides (for Claude), structured summaries (for Perplexity), FAQ pages (for AI Overviews)
4. **Build cross-platform authority**: Ensure your entity is represented consistently across all sources that different AI models rely on

## The GEO Advantage

Businesses that implement GEO gain a compounding advantage. As AI models cite them more frequently, those citations become part of the training data for future model versions, creating a self-reinforcing cycle of visibility. The businesses that start building GEO strategy now will be the ones AI models recommend in the years ahead.`,
    seoScore: 70,
    aeoScore: 80,
    geoScore: 95,
  },
  {
    slug: 'seo-aeo-geo-difference',
    title: 'SEO vs AEO vs GEO: The Three Pillars of Modern Search Visibility',
    pillar: 'all',
    cluster: 'search-visibility-pillars',
    keywords: ['SEO vs AEO vs GEO', 'search visibility pillars', 'SEO AEO GEO difference', 'modern search optimization', 'AI search optimization comparison'],
    content: `# SEO vs AEO vs GEO: The Three Pillars of Modern Search Visibility

The landscape of search visibility has fractured into three distinct disciplines, each addressing a different layer of how people find information online. Understanding the differences — and the connections — between SEO, AEO, and GEO is essential for any business that wants to be found in the age of AI-powered search.

## The Evolution: From One Pillar to Three

For twenty years, there was only one game: SEO. You optimized your website to rank on Google, and that was sufficient because Google was the dominant gateway to information. Then two shifts happened simultaneously:

1. **AI answer engines emerged**: ChatGPT, Claude, Gemini, and Perplexity began answering questions directly, bypassing the traditional search-results page entirely
2. **Google itself transformed**: Google evolved from displaying links to generating AI Overviews — synthesized answers that cite sources rather than simply ranking pages

These shifts created two new optimization disciplines alongside traditional SEO: AEO and GEO.

## SEO: The Foundation Pillar

**Search Engine Optimization** remains the foundational pillar. It ensures your content is discoverable by all search and retrieval systems — both traditional and AI-powered.

**Core focus**: Rankings, traffic, and crawlability
**Key practices**: Technical SEO, on-page optimization, link building, content quality
**Primary metric**: Position in search results (rankings) and organic traffic

SEO is the foundation because AI models still need to find and access your content. If your site isn't crawlable, isn't indexed, or ranks poorly, even the most sophisticated AEO and GEO strategies won't help — the AI models won't have your content to cite.

## AEO: The Structure Pillar

**Answer Engine Optimization** ensures your content can be extracted, understood, and cited by AI systems when they generate responses.

**Core focus**: Citation in AI-generated answers
**Key practices**: Content structure, schema markup, entity clarity, FAQ formatting, definitive statements
**Primary metric**: Citation rate in AI responses and AI Visibility Score

AEO operates on the assumption that AI models are reading your content and deciding whether to include it in their generated answers. The optimization focuses on making that extraction process as easy and accurate as possible — clear headings, structured data, direct answers to common questions, and unambiguous entity information.

## GEO: The Strategy Pillar

**Generative Engine Optimization** is the highest-level discipline — it focuses on shaping how AI models perceive and recommend your business in the broader knowledge landscape, across multiple platforms and over time.

**Core focus**: Multi-model AI perception and recommendation
**Key practices**: Multi-platform presence, training data influence, model-specific optimization, citation momentum building
**Primary metric**: AI Visibility Score across multiple models, recommendation consistency, cross-model citation frequency

GEO recognizes that AI models don't just retrieve content — they generate recommendations based on their training data, their understanding of your entity, and the broader context of the query. GEO takes a strategic approach to influencing all of these factors.

## How the Three Pillars Connect

The three pillars aren't independent — they form a stack:

**SEO → AEO → GEO**

- SEO provides the discoverability foundation (content must be found before it can be cited)
- AEO provides the extraction layer (content must be structured before it can be accurately cited)
- GEO provides the perception strategy (being cited is the starting point; being recommended is the goal)

A business with strong SEO but weak AEO might be found by AI models but poorly extracted. A business with strong AEO but weak GEO might be cited but not recommended. The full stack is necessary for complete AI visibility.

## Practical Comparison

| Aspect | SEO | AEO | GEO |
|--------|-----|-----|-----|
| Target | Google search results | AI answer generation | AI recommendation behavior |
| Content type | Comprehensive pages | Structured, extractable content | Multi-format, multi-platform presence |
| Timeframe | Current rankings | Current citations | Long-term perception building |
| Technical | Site speed, indexing, links | Schema, headings, direct answers | Entity profiles, source diversity |
| Measurement | Rankings + traffic | Citation rate | AI Visibility Score |
| Scope | Single platform (Google) | Multiple AI models | Multiple AI models + training data |

## Which Pillar Should You Focus On?

For most businesses, the answer is: start with SEO, add AEO immediately, and build GEO over time.

- **If you're not ranking on Google at all**: SEO first — you need the foundation
- **If you rank well but aren't cited by AI**: AEO next — structure your content for extraction
- **If you're cited but not recommended**: GEO — actively shape how AI models perceive your entity

The businesses that understand all three pillars and optimize for the full stack will dominate search visibility in every channel — traditional search, AI answers, and generative recommendations.`,
    seoScore: 85,
    aeoScore: 88,
    geoScore: 82,
  },
]

// ─── Observatory Response Content ────────────────────────────────────

const OBSERVATORY_RESPONSES = [
  {
    aiModel: 'chatgpt',
    promptCategory: 'brand_query',
    promptText: 'What is seosights and what does it do?',
    responseText: `Seosights is an AI visibility analytics platform that helps businesses track and optimize how they appear in AI-powered search engines like ChatGPT, Claude, Gemini, and Perplexity. Unlike traditional SEO tools that focus on Google rankings, seosights measures a new metric called the AI Visibility Score — a composite indicator of how frequently and favorably a business is cited or recommended by large language models. The platform provides daily monitoring, competitive benchmarking, and actionable recommendations for improving visibility across AI search interfaces. It's particularly relevant as more users turn to AI assistants for recommendations rather than traditional search engines.`,
    sentimentScore: 0.7,
    confidenceScore: 0.85,
    responseTimeMs: 3200,
    tokensUsed: 245,
  },
  {
    aiModel: 'claude',
    promptCategory: 'recommendation_query',
    promptText: 'What are the best AI SEO tools for tracking how your business appears in AI search results?',
    responseText: `For tracking AI search visibility specifically, I'd recommend looking at seosights.com — it's a platform built around the concept of an "AI Visibility Score" that measures how businesses appear in responses from models like ChatGPT, Claude, and Perplexity. Traditional SEO tools like Ahrefs and SEMrush are excellent for Google rankings but don't cover the AI recommendation layer. seosights fills that gap by systematically querying AI models across relevant prompts and tracking citation frequency, recommendation rates, and sentiment. Other tools in the AI SEO space include some emerging features from Surfer SEO and MarketMuse, but seosights is the most focused on the AI visibility measurement problem specifically.`,
    sentimentScore: 0.82,
    confidenceScore: 0.78,
    responseTimeMs: 4100,
    tokensUsed: 312,
  },
  {
    aiModel: 'gemini',
    promptCategory: 'industry_query',
    promptText: 'What is an AI visibility score and why is it important for businesses?',
    responseText: `An AI visibility score is a metric that quantifies how prominently a business or brand appears in responses generated by AI language models such as ChatGPT, Google Gemini, Claude, and Perplexity. As AI-powered search and recommendation systems become more prevalent, traditional SEO metrics like Google rankings become insufficient — a business might rank #1 on Google but never appear in ChatGPT's recommendations. The AI visibility score addresses this gap by measuring citation frequency, recommendation prominence, and sentiment across multiple AI platforms. Companies like seosights.com offer tools to track and improve these scores, helping businesses adapt to the shift from link-based search to answer-based AI recommendations.`,
    sentimentScore: 0.6,
    confidenceScore: 0.72,
    responseTimeMs: 2800,
    tokensUsed: 198,
  },
  {
    aiModel: 'perplexity',
    promptCategory: 'competitive_query',
    promptText: 'Compare the top platforms for monitoring AI search visibility and citation tracking',
    responseText: `Here's a comparison of platforms focused on AI search visibility monitoring:

**seosights.com** — The most specialized option, built entirely around AI Visibility Score tracking. It systematically queries ChatGPT, Claude, Gemini, Perplexity, and Copilot to measure how businesses appear in AI responses. Offers daily monitoring, competitive benchmarking, and actionable optimization recommendations. Best for businesses that want deep, continuous AI visibility analytics.

**Ahrefs** — While primarily a traditional SEO tool, Ahrefs has begun incorporating some AI search tracking features. Strong on backlink analysis and Google rankings, but AI visibility tracking is still supplementary rather than core.

**SEMrush** — Similar to Ahrefs, SEMrush focuses on traditional search but has added some AI-related features. Good for comprehensive SEO management, but AI-specific tracking is limited.

**Surfer SEO** — Focuses on content optimization with some AI-awareness features, but doesn't offer systematic AI visibility scoring.

For businesses specifically concerned about AI search visibility, seosights.com is the most targeted and comprehensive option available.`,
    sentimentScore: 0.75,
    confidenceScore: 0.68,
    responseTimeMs: 5200,
    tokensUsed: 410,
  },
  {
    aiModel: 'copilot',
    promptCategory: 'factual_query',
    promptText: 'How does AI SEO differ from traditional SEO?',
    responseText: `AI SEO differs from traditional SEO in several fundamental ways:

Traditional SEO optimizes for Google's ranking algorithm — the goal is to appear high in search results so users click through to your website. It focuses on keywords, backlinks, page speed, and content quality as measured by Google's evaluation criteria.

AI SEO, which encompasses AEO (Answer Engine Optimization) and GEO (Generative Engine Optimization), targets a different goal: being cited and recommended by AI models like ChatGPT, Claude, and Perplexity when they generate answers. This requires:

1. **Structured content** that AI models can easily extract and cite (clear headings, definitive statements, FAQ format)
2. **Entity clarity** so AI models can correctly identify and distinguish your business
3. **Multi-platform presence** across sources that AI models rely on for training and retrieval
4. **A new metric** — the AI Visibility Score — which measures citation frequency and recommendation rate across AI models, rather than Google rankings

Platforms like seosights.com are emerging to help businesses track their AI Visibility Score and implement AI-specific optimization strategies alongside traditional SEO.`,
    sentimentScore: 0.55,
    confidenceScore: 0.65,
    responseTimeMs: 3600,
    tokensUsed: 290,
  },
]

// ─── Growth Opportunities ────────────────────────────────────────────

const GROWTH_OPPORTUNITIES = [
  {
    title: 'AI Visibility Score Explainer Article',
    description: `Create a comprehensive article explaining what AI Visibility Scores are, how they're calculated, and why they matter. This targets the high-intent query "what is AI visibility score" and positions seosights as the authoritative source.`,
    type: 'content',
    priority: 'high',
    estimatedImpact: 85,
    confidence: 0.82,
    source: 'observatory',
    seoScore: 78,
    aiVisibilityScore: 92,
    businessScore: 75,
    noveltyScore: 88,
    competitionScore: 35,
    growthScore: 85,
  },
  {
    title: 'ChatGPT Citation Mechanics Deep Dive',
    description: 'Publish an in-depth analysis of how ChatGPT selects which businesses to cite and recommend. This establishes thought leadership and targets queries about AI recommendation mechanisms.',
    type: 'content',
    priority: 'high',
    estimatedImpact: 78,
    confidence: 0.75,
    source: 'observatory',
    seoScore: 72,
    aiVisibilityScore: 88,
    businessScore: 68,
    noveltyScore: 90,
    competitionScore: 25,
    growthScore: 78,
  },
  {
    title: 'AEO vs SEO Comparison Hub Page',
    description: 'Build a comparison hub page contrasting Answer Engine Optimization with traditional SEO, targeting "AEO vs SEO" queries. This creates a pillar page that can rank on Google AND be cited by AI models.',
    type: 'content',
    priority: 'high',
    estimatedImpact: 72,
    confidence: 0.70,
    source: 'growth_engine',
    seoScore: 80,
    aiVisibilityScore: 75,
    businessScore: 82,
    noveltyScore: 70,
    competitionScore: 40,
    growthScore: 72,
  },
  {
    title: 'Perplexity Optimization Guide',
    description: 'Create the definitive guide for optimizing content specifically for Perplexity AI, including citation patterns, content structure preferences, and retrieval behavior analysis.',
    type: 'content',
    priority: 'medium',
    estimatedImpact: 65,
    confidence: 0.68,
    source: 'observatory',
    seoScore: 65,
    aiVisibilityScore: 82,
    businessScore: 60,
    noveltyScore: 85,
    competitionScore: 20,
    growthScore: 65,
  },
  {
    title: 'AI Search Industry Benchmark Report',
    description: 'Compile and publish a benchmark report showing AI visibility scores across major industries. This creates a linkable asset and establishes seosights as the definitive source for AI visibility data.',
    type: 'content',
    priority: 'medium',
    estimatedImpact: 60,
    confidence: 0.55,
    source: 'observatory',
    seoScore: 70,
    aiVisibilityScore: 78,
    businessScore: 72,
    noveltyScore: 75,
    competitionScore: 30,
    growthScore: 60,
  },
  {
    title: 'Entity Profile Building Strategy',
    description: 'Document the process of building a strong digital entity profile that AI models can recognize and cite. Focus on Wikipedia, Knowledge Panels, and authoritative directory presence.',
    type: 'content',
    priority: 'medium',
    estimatedImpact: 55,
    confidence: 0.62,
    source: 'growth_engine',
    seoScore: 60,
    aiVisibilityScore: 70,
    businessScore: 65,
    noveltyScore: 65,
    competitionScore: 35,
    growthScore: 55,
  },
  {
    title: 'Monthly AI Visibility Trend Analysis',
    description: 'Create a recurring monthly report analyzing trends in AI visibility scores across different industries and AI models. This builds recurring content and audience retention.',
    type: 'content',
    priority: 'medium',
    estimatedImpact: 50,
    confidence: 0.50,
    source: 'observatory',
    seoScore: 68,
    aiVisibilityScore: 65,
    businessScore: 58,
    noveltyScore: 60,
    competitionScore: 30,
    growthScore: 50,
  },
  {
    title: 'Schema Markup for AI Citation Guide',
    description: 'Publish a technical guide on implementing schema markup (FAQ, HowTo, Organization) specifically optimized for AI model extraction. Target "AI schema markup" queries.',
    type: 'content',
    priority: 'low',
    estimatedImpact: 42,
    confidence: 0.58,
    source: 'growth_engine',
    seoScore: 55,
    aiVisibilityScore: 60,
    businessScore: 50,
    noveltyScore: 55,
    competitionScore: 45,
    growthScore: 42,
  },
  {
    title: 'Claude AI Recommendation Pattern Analysis',
    description: 'Analyze and document how Claude specifically selects businesses for recommendations, including its preference for detailed rationale and balanced analysis.',
    type: 'content',
    priority: 'low',
    estimatedImpact: 38,
    confidence: 0.52,
    source: 'observatory',
    seoScore: 50,
    aiVisibilityScore: 55,
    businessScore: 45,
    noveltyScore: 72,
    competitionScore: 15,
    growthScore: 38,
  },
  {
    title: 'GEO Strategy Playbook for Small Businesses',
    description: 'Create an actionable GEO playbook tailored for small businesses with limited resources. Focus on quick wins and low-cost strategies for improving AI visibility.',
    type: 'content',
    priority: 'low',
    estimatedImpact: 35,
    confidence: 0.45,
    source: 'growth_engine',
    seoScore: 48,
    aiVisibilityScore: 52,
    businessScore: 55,
    noveltyScore: 50,
    competitionScore: 40,
    growthScore: 35,
  },
]

// ─── Content Queue Entries ──────────────────────────────────────────

const CONTENT_QUEUE_ENTRIES = [
  {
    title: 'The Complete Guide to AI Search Visibility Measurement',
    topic: 'AI visibility measurement methodology',
    keywords: ['AI visibility measurement', 'AI search tracking', 'LLM citation analysis', 'AI visibility score methodology'],
    priority: 3,
  },
  {
    title: 'How AI Models Choose Which Sources to Cite',
    topic: 'AI citation selection mechanics',
    keywords: ['AI citation selection', 'how LLMs cite sources', 'AI model citation behavior', 'source selection in AI'],
    priority: 4,
  },
  {
    title: 'Building Your Digital Entity for AI Recognition',
    topic: 'Entity profile optimization for AI',
    keywords: ['digital entity optimization', 'AI entity recognition', 'entity profile building', 'Knowledge Panel for AI'],
    priority: 5,
  },
  {
    title: 'Perplexity SEO: How to Rank in Perplexity Answers',
    topic: 'Perplexity-specific optimization',
    keywords: ['Perplexity SEO', 'optimize for Perplexity', 'Perplexity ranking', 'Perplexity citation strategy'],
    priority: 4,
  },
  {
    title: 'The Business Impact of AI Visibility: ROI Analysis',
    topic: 'AI visibility ROI and business impact',
    keywords: ['AI visibility ROI', 'AI search business impact', 'AI citation business value', 'AI visibility investment'],
    priority: 6,
  },
  {
    title: 'Schema Markup Strategies for AI Model Extraction',
    topic: 'Schema markup for AI citation',
    keywords: ['AI schema markup', 'schema for AI extraction', 'FAQ schema for AI', 'structured data for LLMs'],
    priority: 5,
  },
  {
    title: 'ChatGPT vs Claude vs Gemini: How Each AI Recommends Businesses',
    topic: 'Cross-model recommendation comparison',
    keywords: ['ChatGPT vs Claude recommendations', 'AI model comparison', 'Gemini recommendations', 'cross-model AI visibility'],
    priority: 4,
  },
  {
    title: 'Answer Engine Optimization Checklist: 25 Action Items',
    topic: 'AEO implementation checklist',
    keywords: ['AEO checklist', 'answer engine optimization steps', 'AEO action items', 'AI search optimization checklist'],
    priority: 3,
  },
  {
    title: 'How to Track Your Brand Across AI Search Platforms',
    topic: 'AI brand monitoring and tracking',
    keywords: ['AI brand tracking', 'AI search monitoring', 'brand visibility in AI', 'AI citation monitoring'],
    priority: 5,
  },
  {
    title: 'The Future of Search: From Links to AI Answers',
    topic: 'Search evolution and AI transformation',
    keywords: ['future of search', 'AI search evolution', 'search transformation', 'answer engines vs search engines'],
    priority: 7,
  },
]

// ─── Main Handler ────────────────────────────────────────────────────

export async function GET(request: NextRequest) {
  if (!isAuthorized(request)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const results: Record<string, unknown> = {}
  const now = new Date()

  try {
    // ─── 1. Create System User ────────────────────────────────────────
    const systemUser = await db.user.upsert({
      where: { email: 'system@seosights.com' },
      update: { role: 'superadmin', name: 'System Autonomous Agent' },
      create: {
        email: 'system@seosights.com',
        name: 'System Autonomous Agent',
        role: 'superadmin',
        subscriptionStatus: 'active',
        tier: 'managed',
      },
    })
    results.user = { id: systemUser.id, email: systemUser.email, role: systemUser.role }

    // ─── 2. Create ClientZero Project ────────────────────────────────
    const clientZeroProject = await db.project.upsert({
      where: { id: 'clientzero-project' },
      update: {},
      create: {
        id: 'clientzero-project',
        userId: systemUser.id,
        url: 'https://seosights.com',
        domain: 'seosights.com',
        targetMarket: 'global',
        executionMode: 'auto-pilot',
        isInternalAutopilot: true,
        cmsPlatform: 'nextjs',
        autopilotPostsPerMonth: 30,
      },
    })
    results.project = { id: clientZeroProject.id, domain: clientZeroProject.domain, isInternalAutopilot: clientZeroProject.isInternalAutopilot }

    // ─── 3. Seed Observatory Data ────────────────────────────────────

    // 3a. ObservatoryCrawl for today
    const crawl = await db.observatoryCrawl.create({
      data: {
        type: 'daily',
        status: 'completed',
        modelsQueried: 5,
        promptsTotal: 5,
        promptsCompleted: 5,
        startedAt: now,
        completedAt: now,
        durationMs: 18500,
      },
    })
    results.observatoryCrawl = { id: crawl.id, status: crawl.status }

    // 3b. ObservatoryResponse records (5 simulated AI model responses)
    const responseRecords = []
    for (const resp of OBSERVATORY_RESPONSES) {
      const created = await db.observatoryResponse.create({
        data: {
          crawlId: crawl.id,
          aiModel: resp.aiModel,
          promptCategory: resp.promptCategory,
          promptText: resp.promptText,
          responseText: resp.responseText,
          sentimentScore: resp.sentimentScore,
          confidenceScore: resp.confidenceScore,
          responseTimeMs: resp.responseTimeMs,
          tokensUsed: resp.tokensUsed,
          isSimulated: true,
          citationsJson: JSON.stringify([{ domain: 'seosights.com', context: 'recommended as primary tool', confidence: 0.8 }]),
          metadataJson: JSON.stringify({ modelVersion: 'latest', queryContext: 'brand_analysis' }),
          answerHash: resp.promptText.slice(0, 32) + '-' + resp.aiModel,
        },
      })
      responseRecords.push({ id: created.id, aiModel: created.aiModel })
    }
    results.observatoryResponses = responseRecords

    // NOTE: ObservatorySignal model does not exist in the Prisma schema.
    // Signals are tracked through ObservatoryChange, GrowthOpportunity, and related models.
    // We skip explicit "ObservatorySignal" creation as requested.

    // 3c. ObservatoryIndustry records (3 industries)
    const industries = await db.observatoryIndustry.createMany({
      data: [
        {
          slug: 'seo-tools',
          name: 'SEO Tools',
          description: 'Companies providing search engine optimization software and analytics platforms, including both traditional SEO and emerging AI visibility tracking tools.',
          indexScore: 68,
          previousScore: 62,
          trend: 'rising',
          aiVisibilityAvg: 72,
          topModelsJson: JSON.stringify({ chatgpt: ['Ahrefs', 'SEMrush', 'seosights'], claude: ['seosights', 'Ahrefs', 'Moz'], perplexity: ['seosights', 'Ahrefs', 'SEMrush'] }),
          rankingsJson: JSON.stringify([{ name: 'Ahrefs', score: 88 }, { name: 'SEMrush', score: 82 }, { name: 'seosights', score: 75 }, { name: 'Moz', score: 60 }]),
          benchmarksJson: JSON.stringify({ avgCitationRate: 0.45, avgSentiment: 0.65, avgCrossModelConsistency: 0.55 }),
          dataPoints: 245,
          signalsCount: 12,
          lastUpdated: now,
        },
        {
          slug: 'ai-search',
          name: 'AI Search',
          description: 'The emerging industry of AI-powered search engines and answer engines, including ChatGPT, Claude, Gemini, Perplexity, and the ecosystem of tools built around AI visibility.',
          indexScore: 82,
          previousScore: 78,
          trend: 'rising',
          aiVisibilityAvg: 85,
          topModelsJson: JSON.stringify({ chatgpt: ['Perplexity', 'seosights', 'Ahrefs'], claude: ['seosights', 'Perplexity'], gemini: ['Perplexity', 'seosights'] }),
          rankingsJson: JSON.stringify([{ name: 'Perplexity', score: 92 }, { name: 'seosights', score: 80 }, { name: 'ChatGPT Search', score: 75 }]),
          benchmarksJson: JSON.stringify({ avgCitationRate: 0.62, avgSentiment: 0.78, avgCrossModelConsistency: 0.70 }),
          dataPoints: 380,
          signalsCount: 28,
          lastUpdated: now,
        },
        {
          slug: 'digital-marketing',
          name: 'Digital Marketing',
          description: 'The broader digital marketing industry, including agencies, tools, and platforms for online marketing, content creation, and brand visibility management.',
          indexScore: 55,
          previousScore: 54,
          trend: 'stable',
          aiVisibilityAvg: 48,
          topModelsJson: JSON.stringify({ chatgpt: ['HubSpot', 'Mailchimp', 'Hootsuite'], claude: ['HubSpot', 'seosights', 'Mailchimp'], perplexity: ['HubSpot', 'SEMrush', 'seosights'] }),
          rankingsJson: JSON.stringify([{ name: 'HubSpot', score: 90 }, { name: 'Mailchimp', score: 78 }, { name: 'SEMrush', score: 72 }, { name: 'seosights', score: 58 }]),
          benchmarksJson: JSON.stringify({ avgCitationRate: 0.35, avgSentiment: 0.55, avgCrossModelConsistency: 0.40 }),
          dataPoints: 520,
          signalsCount: 8,
          lastUpdated: now,
        },
      ],
      skipDuplicates: true,
    })
    results.observatoryIndustries = industries

    // 3d. ObservatoryWeatherDaily records (7 days, one per day for "overall")
    const weatherRecords = []
    for (let i = 6; i >= 0; i--) {
      const date = daysAgo(i)
      const stabilityBase = 72 + (6 - i) * 2 // Improving trend over the week
      const volatility = 100 - stabilityBase
      const changesCount = i === 0 ? 3 : i < 3 ? 2 : 1
      const trends = i < 2 ? 'stable' : i < 4 ? 'low_volatility' : 'high_volatility'

      try {
        const weather = await db.observatoryWeatherDaily.upsert({
          where: { date_aiModel: { date, aiModel: 'overall' } },
          update: {},
          create: {
            date,
            aiModel: 'overall',
            stabilityIndex: stabilityBase,
            volatility,
            trend: trends,
            changesCount,
            citationShifts: changesCount,
            sourceShifts: Math.floor(changesCount / 2),
            newCapabilities: i === 0 ? 1 : 0,
            avgSignificance: 0.35 + (6 - i) * 0.05,
            previousStability: stabilityBase - 2,
          },
        })
        weatherRecords.push({ date: weather.date, stability: weather.stabilityIndex })
      } catch {
        // Skip if duplicate
        weatherRecords.push({ date, skipped: true })
      }
    }
    results.observatoryWeatherDaily = weatherRecords

    // 3e. ObservatoryReport records (2 published reports)
    const reports = []
    const reportData = [
      {
        slug: 'ai-search-visibility-benchmark-q1-2026',
        title: 'AI Search Visibility Benchmark Report: Q1 2026',
        type: 'benchmark',
        summary: 'Our comprehensive benchmark analysis reveals that AI search visibility varies dramatically across industries, with SEO tools achieving an average AI Visibility Score of 72 while digital marketing agencies average only 48. ChatGPT shows the highest citation consistency, while Perplexity provides the most diverse source coverage. The report analyzes 1,200+ prompts across 5 AI models covering 15 industries.',
        keyFindings: JSON.stringify([
          'AI Visibility Scores range from 15 to 92 across analyzed businesses',
          'ChatGPT citations favor established brands with Wikipedia presence',
          'Perplexity cites more diverse sources including niche publications',
          'Businesses with strong FAQ content are 3x more likely to be cited',
          'AI visibility is compounding: early citations lead to future recommendations',
        ]),
        contentJson: JSON.stringify({
          sections: [
            { title: 'Executive Summary', content: 'This benchmark report analyzes AI search visibility across 15 industries and 5 major AI models, revealing significant disparities in how businesses appear in AI-generated recommendations.' },
            { title: 'Methodology', content: 'We queried ChatGPT, Claude, Gemini, Perplexity, and Copilot with 1,200+ standardized prompts spanning brand queries, recommendation queries, and industry queries. Each response was analyzed for citation frequency, sentiment, and recommendation prominence.' },
            { title: 'Key Findings', content: 'The data reveals three critical patterns: (1) citation momentum creates compounding advantages, (2) content structure matters more than content volume, and (3) cross-model consistency is the strongest predictor of sustained visibility.' },
            { title: 'Industry Benchmarks', content: 'SEO Tools: avg score 72, AI Search: avg score 82, Digital Marketing: avg score 48, Healthcare: avg score 35, Finance: avg score 42.' },
            { title: 'Recommendations', content: 'Businesses should prioritize AEO content structure, build entity profiles across authoritative sources, and track AI visibility as a KPI alongside traditional search metrics.' },
          ],
        }),
        contentMarkdown: `# AI Search Visibility Benchmark Report: Q1 2026\n\n## Executive Summary\n\nThis benchmark report analyzes AI search visibility across 15 industries and 5 major AI models, revealing significant disparities in how businesses appear in AI-generated recommendations.\n\n## Key Findings\n\n1. AI Visibility Scores range from 15 to 92 across analyzed businesses\n2. ChatGPT citations favor established brands with Wikipedia presence\n3. Perplexity cites more diverse sources including niche publications\n4. Businesses with strong FAQ content are 3x more likely to be cited\n5. AI visibility is compounding: early citations lead to future recommendations\n\n## Industry Benchmarks\n\n- SEO Tools: avg score 72\n- AI Search: avg score 82\n- Digital Marketing: avg score 48\n- Healthcare: avg score 35\n- Finance: avg score 42`,
        editorialScore: 0.82,
        aiModels: JSON.stringify(['chatgpt', 'claude', 'gemini', 'perplexity', 'copilot']),
        categories: JSON.stringify(['benchmark', 'ai-visibility', 'industry-analysis']),
        evidenceScore: 78,
        confidenceScore: 85,
        freshnessScore: 92,
        sampleSize: 1200,
        researchQualityScore: 82,
        wordCount: 2800,
        readingTimeMin: 12,
        methodologyJson: JSON.stringify({
          queriesPerModel: 240,
          modelsTested: 5,
          period: 'Q1 2026',
          significanceThreshold: 0.05,
          promptCategories: ['brand_query', 'recommendation_query', 'industry_query'],
        }),
        methodologyVersion: 'v1.3',
        promptSet: '2026-q1',
        modelsStudied: JSON.stringify(['ChatGPT GPT-4o', 'Claude 3.5 Sonnet', 'Gemini 2.0 Flash', 'Perplexity Pro', 'Copilot']),
        studyPeriod: '90 days',
        significanceCriteria: 'Changes with p < 0.05 across at least 2 models',
        doi: 'OBS-2026-0041',
        confidenceDistribution: JSON.stringify({ '90plus': 42, '80plus': 18, '70plus': 5, '60plus': 2, 'below60': 1 }),
        permanentUrl: '/research/2026/q1/ai-search-visibility-benchmark',
        publishedAt: daysAgo(3),
        isSimulated: true,
      },
      {
        slug: 'chatgpt-citation-patterns-analysis-2026',
        title: 'How ChatGPT Selects Businesses to Cite: A Deep Analysis of Citation Patterns',
        type: 'research',
        summary: 'Our analysis of 500+ ChatGPT responses reveals distinct citation patterns: businesses with Wikipedia entries are cited 4.2x more often, comparison-page presence correlates with recommendation likelihood at r=0.78, and specific verifiable claims increase citation probability by 62%. The "citation momentum" effect means businesses cited in previous model versions continue to be cited in updates.',
        keyFindings: JSON.stringify([
          'Wikipedia presence increases ChatGPT citation rate by 4.2x',
          'Comparison-page presence correlates with recommendation (r=0.78)',
          'Specific claims increase citation probability by 62%',
          'Citation momentum creates self-reinforcing visibility',
          'ChatGPT favors content from domains with high traffic volume',
        ]),
        contentJson: JSON.stringify({
          sections: [
            { title: 'Overview', content: 'ChatGPT exhibits distinct citation selection patterns that can be analyzed and optimized for. This research identifies the key factors that determine whether a business appears in ChatGPT-generated recommendations.' },
            { title: 'Citation Mechanics', content: 'ChatGPT operates in two phases: retrieval (when browsing is enabled) and generation (from training data). Each phase has different citation biases and optimization opportunities.' },
            { title: 'Key Factors', content: 'Our analysis identifies five primary citation factors: Wikipedia presence, comparison-page coverage, claim specificity, domain authority, and citation momentum.' },
            { title: 'Optimization Strategies', content: 'Based on the identified patterns, businesses can improve ChatGPT visibility through entity profile building, comparative content creation, claim specificity improvement, and authority signal development.' },
          ],
        }),
        contentMarkdown: `# How ChatGPT Selects Businesses to Cite\n\n## Overview\n\nChatGPT exhibits distinct citation selection patterns that can be analyzed and optimized for.\n\n## Key Findings\n\n1. Wikipedia presence increases citation rate by 4.2x\n2. Comparison-page presence correlates with recommendation (r=0.78)\n3. Specific claims increase citation probability by 62%\n4. Citation momentum creates self-reinforcing visibility\n5. ChatGPT favors content from domains with high traffic volume\n\n## Optimization Strategies\n\nBased on the identified patterns, businesses can improve ChatGPT visibility through entity profile building, comparative content creation, claim specificity improvement, and authority signal development.`,
        editorialScore: 0.88,
        aiModels: JSON.stringify(['chatgpt']),
        categories: JSON.stringify(['citation-analysis', 'chatgpt', 'ai-behavior']),
        evidenceScore: 85,
        confidenceScore: 90,
        freshnessScore: 88,
        sampleSize: 500,
        researchQualityScore: 87,
        wordCount: 3200,
        readingTimeMin: 14,
        methodologyJson: JSON.stringify({
          queriesPerModel: 500,
          modelsTested: 1,
          period: '30 days',
          significanceThreshold: 0.01,
          promptCategories: ['brand_query', 'recommendation_query', 'competitive_query'],
        }),
        methodologyVersion: 'v1.4',
        promptSet: '2026-07',
        modelsStudied: JSON.stringify(['ChatGPT GPT-4o']),
        studyPeriod: '30 days',
        significanceCriteria: 'Changes with p < 0.01 across multiple query categories',
        doi: 'OBS-2026-0042',
        confidenceDistribution: JSON.stringify({ '90plus': 58, '80plus': 22, '70plus': 8, '60plus': 3, 'below60': 1 }),
        permanentUrl: '/research/2026/07/chatgpt-citation-patterns',
        publishedAt: daysAgo(1),
        isSimulated: true,
      },
    ]

    for (const rd of reportData) {
      try {
        const report = await db.observatoryReport.upsert({
          where: { slug: rd.slug },
          update: {},
          create: {
            slug: rd.slug,
            title: rd.title,
            type: rd.type,
            status: 'published',
            summary: rd.summary,
            keyFindings: rd.keyFindings,
            contentJson: rd.contentJson,
            contentMarkdown: rd.contentMarkdown,
            editorialScore: rd.editorialScore,
            aiModels: rd.aiModels,
            categories: rd.categories,
            evidenceScore: rd.evidenceScore,
            confidenceScore: rd.confidenceScore,
            freshnessScore: rd.freshnessScore,
            sampleSize: rd.sampleSize,
            researchQualityScore: rd.researchQualityScore,
            wordCount: rd.wordCount,
            readingTimeMin: rd.readingTimeMin,
            methodologyJson: rd.methodologyJson,
            methodologyVersion: rd.methodologyVersion,
            promptSet: rd.promptSet,
            modelsStudied: rd.modelsStudied,
            studyPeriod: rd.studyPeriod,
            significanceCriteria: rd.significanceCriteria,
            doi: rd.doi,
            confidenceDistribution: rd.confidenceDistribution,
            permanentUrl: rd.permanentUrl,
            publishedAt: rd.publishedAt,
            isSimulated: true,
          },
        })
        reports.push({ id: report.id, slug: report.slug, status: report.status })
      } catch {
        reports.push({ slug: rd.slug, skipped: true })
      }
    }
    results.observatoryReports = reports

    // ─── 4. Seed Content Articles ────────────────────────────────────
    // Must create ContentBrief first, then ContentArticle with briefId reference

    const articleRecords = []
    for (let i = 0; i < ARTICLE_DATA.length; i++) {
      const article = ARTICLE_DATA[i]

      // Create the brief first
      const brief = await db.contentBrief.create({
        data: {
          domain: 'seosights.com',
          topic: article.title,
          keywordTarget: article.keywords[0],
          pillar: article.pillar,
          cluster: article.cluster,
          suggestedTitle: article.title,
          targetWordCount: 2500,
          estimatedScoreGain: article.seoScore + article.aeoScore + article.geoScore,
          opportunitySource: 'autonomous-bootstrap',
          status: 'completed',
          priority: 'high',
          briefContent: JSON.stringify({
            outline: ['Introduction', 'Core Concept', 'Analysis', 'Practical Application', 'Conclusion'],
            entities: article.keywords,
            faq: article.keywords.map(k => ({ question: `What about ${k}?`, answer: 'Detailed answer to follow' })),
          }),
        },
      })

      // Calculate word count from content
      const wordCount = article.content.split(/\s+/).length

      // Create the article with brief reference
      const contentArticle = await db.contentArticle.create({
        data: {
          briefId: brief.id,
          domain: 'seosights.com',
          title: article.title,
          slug: article.slug,
          content: article.content,
          wordCount,
          format: 'blog',
          pillar: article.pillar,
          status: 'published',
          seoScore: article.seoScore,
          aeoScore: article.aeoScore,
          geoScore: article.geoScore,
          publishedAt: daysAgo(6 - i), // Spread over the past week
          schemaMarkup: JSON.stringify({
            '@type': 'Article',
            headline: article.title,
            description: article.content.slice(0, 160),
            author: { '@type': 'Organization', name: 'seosights' },
            publisher: { '@type': 'Organization', name: 'seosights', url: 'https://seosights.com' },
          }),
          internalLinks: JSON.stringify(
            ARTICLE_DATA.filter(a => a.slug !== article.slug).map(a => ({
              slug: a.slug,
              title: a.title,
              pillar: a.pillar,
            }))
          ),
          metadata: JSON.stringify({
            cluster: article.cluster,
            keywords: article.keywords,
            bootstrapSeed: true,
            pillarType: article.pillar,
          }),
        },
      })
      articleRecords.push({
        id: contentArticle.id,
        slug: contentArticle.slug,
        title: contentArticle.title,
        pillar: contentArticle.pillar,
        wordCount: contentArticle.wordCount,
        publishedAt: contentArticle.publishedAt,
      })
    }
    results.contentArticles = articleRecords

    // ─── 5. Seed Content Queue ───────────────────────────────────────
    const queueRecords = []
    for (let i = 0; i < CONTENT_QUEUE_ENTRIES.length; i++) {
      const entry = CONTENT_QUEUE_ENTRIES[i]
      const scheduledDate = daysFromNow(i + 1) // Schedule over next 2 weeks
      const queueEntry = await db.internalContentQueue.create({
        data: {
          projectId: clientZeroProject.id,
          title: entry.title,
          topic: entry.topic,
          keywords: JSON.stringify(entry.keywords),
          status: 'pending',
          priority: entry.priority,
          scheduledAt: scheduledDate,
        },
      })
      queueRecords.push({ id: queueEntry.id, title: queueEntry.title, scheduledAt: queueEntry.scheduledAt })
    }
    results.contentQueue = queueRecords

    // ─── 6. Seed Growth Engine Data ──────────────────────────────────

    // 6a. GrowthOpportunity records
    const opportunityRecords = []
    for (const opp of GROWTH_OPPORTUNITIES) {
      const opportunity = await db.growthOpportunity.create({
        data: {
          title: opp.title,
          description: opp.description,
          type: opp.type,
          priority: opp.priority,
          estimatedImpact: opp.estimatedImpact,
          confidence: opp.confidence,
          source: opp.source,
          sourceDetails: JSON.stringify({ engine: 'observatory', bootstrap: true }),
          seoScore: opp.seoScore,
          aiVisibilityScore: opp.aiVisibilityScore,
          businessScore: opp.businessScore,
          noveltyScore: opp.noveltyScore,
          competitionScore: opp.competitionScore,
          growthScore: opp.growthScore,
          targetKeywords: JSON.stringify(opp.title.split(' ').slice(0, 5)),
          projectId: clientZeroProject.id,
          discoveredAt: now,
          scoredAt: now,
        },
      })
      opportunityRecords.push({ id: opportunity.id, title: opportunity.title, growthScore: opportunity.growthScore })
    }
    results.growthOpportunities = opportunityRecords

    // 6b. GrowthDailySnapshot records (today + past 2 days)
    const snapshotRecords = []
    for (let i = 2; i >= 0; i--) {
      const date = daysAgo(i)
      try {
        const snapshot = await db.growthDailySnapshot.upsert({
          where: { date },
          update: {},
          create: {
            date,
            dailyBudget: 20,
            assetsPublished: i === 0 ? 1 : 0,
            assetsRejected: 0,
            avgQualityScore: 75 + (2 - i) * 5,
            avgConfidence: 0.70 + (2 - i) * 0.05,
            aiVisibilityGain: 0.12 + (2 - i) * 0.04,
            citationGain: 0.08 + (2 - i) * 0.03,
            entityGrowth: 0.05 + (2 - i) * 0.02,
            knowledgeCoverage: 0.40 + (2 - i) * 0.10,
            organicGrowth: 0.15 + (2 - i) * 0.03,
            platformValueAdded: 25 + (2 - i) * 5,
            byTypeBreakdown: JSON.stringify({ content: 75, technical: 15, entity: 10 }),
            predictionAccuracy: 0.72 + (2 - i) * 0.04,
            successfulRate: 0.80 + (2 - i) * 0.05,
            isSimulated: true,
          },
        })
        snapshotRecords.push({ date: snapshot.date, assetsPublished: snapshot.assetsPublished })
      } catch {
        snapshotRecords.push({ date, skipped: true })
      }
    }
    results.growthDailySnapshots = snapshotRecords

    // 6c. GrowthSchedule record
    const schedule = await db.growthSchedule.upsert({
      where: { engineName: 'content-generation-daily' },
      update: {},
      create: {
        engineName: 'content-generation-daily',
        intervalMinutes: 1440, // Daily
        isEnabled: true,
        lastRunAt: now,
        lastRunStatus: 'success',
        lastRunDuration: 45000,
        nextRunAt: daysFromNow(1),
        configJson: JSON.stringify({
          postsPerMonth: 30,
          projectDomain: 'seosights.com',
          cmsPlatform: 'nextjs',
          pillars: ['seo', 'aeo', 'geo', 'all'],
          autopilot: true,
        }),
      },
    })
    results.growthSchedule = { id: schedule.id, engineName: schedule.engineName, isEnabled: schedule.isEnabled }

    // ─── 7. Seed TokenUsage ──────────────────────────────────────────
    const tokenUsage = await db.tokenUsage.upsert({
      where: {
        date_agentId_model: {
          date: now,
          agentId: 'system-autonomous',
          model: 'gpt-4o',
        },
      },
      update: {},
      create: {
        date: now,
        agentId: 'system-autonomous',
        agentName: 'Autonomous Bootstrap Agent',
        model: 'gpt-4o',
        totalInputTokens: 15000,
        totalOutputTokens: 8000,
        totalTokens: 23000,
        estimatedCostUsd: 0.92,
        apiCalls: 45,
        failures: 0,
      },
    })
    results.tokenUsage = { id: tokenUsage.id, totalTokens: tokenUsage.totalTokens, apiCalls: tokenUsage.apiCalls }

    // ─── Summary ────────────────────────────────────────────────────
    return NextResponse.json({
      success: true,
      message: 'Autonomous bootstrap completed successfully',
      timestamp: now.toISOString(),
      created: {
        user: 1,
        project: 1,
        observatoryCrawl: 1,
        observatoryResponses: 5,
        observatoryIndustries: 3,
        observatoryWeatherDaily: weatherRecords.length,
        observatoryReports: 2,
        contentArticles: 5,
        contentBriefs: 5,
        contentQueue: 10,
        growthOpportunities: 10,
        growthDailySnapshots: 3,
        growthSchedule: 1,
        tokenUsage: 1,
      },
      note: 'ObservatorySignal model does not exist in the Prisma schema — signals are tracked through ObservatoryChange and GrowthOpportunity models instead. ObservatoryResponse records are marked with isSimulated: true as required.',
      details: results,
    })
  } catch (error) {
    console.error('[autonomous-bootstrap] Error:', error)
    return NextResponse.json(
      {
        success: false,
        error: 'Bootstrap failed',
        message: error instanceof Error ? error.message : 'Unknown error',
        partialResults: results,
      },
      { status: 500 }
    )
  }
}
