'use client'

/**
 * Editorial Calendar — Weekly view with scheduled content
 *
 * Visual calendar showing content scheduled across the week,
 * color-coded by content type with auto-generate capabilities.
 */

import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { ScrollArea, ScrollBar } from '@/components/ui/scroll-area'
import {
  CalendarDays,
  Sparkles,
  ChevronLeft,
  ChevronRight,
  Loader2,
} from 'lucide-react'

// ── Types ───────────────────────────────────────────────────────────────

type ContentType = 'blog' | 'programmatic' | 'linkedin' | 'newsletter' | 'docs' | 'vs_page'
type ContentStatus = 'scheduled' | 'writing' | 'review' | 'approved' | 'published'

interface CalendarEntry {
  id: string
  title: string
  contentTypeId: string
  contentTypeLabel?: string
  estimatedScoreGain: number
  status: string
  date: string
  briefId?: string | null
  autoGenerated?: boolean
}

interface DaySchedule {
  date: string
  dayName: string
  entries: CalendarEntry[]
}

// ── Color Map ───────────────────────────────────────────────────────────

const TYPE_COLORS: Record<string, { bg: string; text: string; border: string; dot: string }> = {
  blog: { bg: 'bg-emerald-500/15', text: 'text-emerald-400', border: 'border-emerald-500/30', dot: 'bg-emerald-400' },
  programmatic: { bg: 'bg-blue-500/15', text: 'text-blue-400', border: 'border-blue-500/30', dot: 'bg-blue-400' },
  linkedin: { bg: 'bg-violet-500/15', text: 'text-violet-400', border: 'border-violet-500/30', dot: 'bg-violet-400' },
  newsletter: { bg: 'bg-amber-500/15', text: 'text-amber-400', border: 'border-amber-500/30', dot: 'bg-amber-400' },
  docs: { bg: 'bg-gray-500/15', text: 'text-gray-400', border: 'border-gray-500/30', dot: 'bg-gray-400' },
  vs_page: { bg: 'bg-cyan-500/15', text: 'text-cyan-400', border: 'border-cyan-500/30', dot: 'bg-cyan-400' },
}

const STATUS_BADGES: Record<string, { label: string; color: string }> = {
  scheduled: { label: 'Scheduled', color: 'bg-white/10 text-white/70' },
  writing: { label: 'Writing', color: 'bg-amber-500/20 text-amber-400' },
  review: { label: 'Review', color: 'bg-violet-500/20 text-violet-400' },
  approved: { label: 'Approved', color: 'bg-emerald-500/20 text-emerald-400' },
  published: { label: 'Published', color: 'bg-emerald-500/30 text-emerald-300' },
}

const SHORT_DAY_NAMES: Record<string, string> = {
  Monday: 'Mon',
  Tuesday: 'Tue',
  Wednesday: 'Wed',
  Thursday: 'Thu',
  Friday: 'Fri',
  Saturday: 'Sat',
  Sunday: 'Sun',
}

// ── Fallback Data ───────────────────────────────────────────────────────

function generateFallbackCalendar(): DaySchedule[] {
  const today = new Date()
  const dayOfWeek = today.getDay()
  const monday = new Date(today)
  monday.setDate(today.getDate() - ((dayOfWeek + 6) % 7))

  const dayNames = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
  const sampleEntries: Omit<CalendarEntry, 'id' | 'date'>[] = [
    { title: 'AI Visibility for Dentists', contentTypeId: 'blog', estimatedScoreGain: 6, status: 'approved' },
    { title: 'LLM SEO Guide (50 cities)', contentTypeId: 'programmatic', estimatedScoreGain: 8, status: 'writing' },
    { title: 'Why AI Search Changes SEO', contentTypeId: 'linkedin', estimatedScoreGain: 3, status: 'scheduled' },
    { title: 'Monthly AI Visibility Report', contentTypeId: 'newsletter', estimatedScoreGain: 2, status: 'review' },
    { title: 'API Reference v2.1', contentTypeId: 'docs', estimatedScoreGain: 1, status: 'published' },
    { title: 'Schema Markup for AI Crawlers', contentTypeId: 'blog', estimatedScoreGain: 4, status: 'writing' },
    { title: 'Citation Building Strategy', contentTypeId: 'blog', estimatedScoreGain: 7, status: 'scheduled' },
    { title: 'GEO Ranking Optimization', contentTypeId: 'blog', estimatedScoreGain: 5, status: 'scheduled' },
  ]

  const result: DaySchedule[] = []
  const todayStr = today.toISOString().split('T')[0]

  for (let i = 0; i < 7; i++) {
    const d = new Date(monday)
    d.setDate(monday.getDate() + i)
    const iso = d.toISOString().split('T')[0]
    const isToday = iso === todayStr
    const dayEntries: CalendarEntry[] = []
    if (i === 0) dayEntries.push({ ...sampleEntries[0], id: '1', date: iso })
    if (i === 1) dayEntries.push({ ...sampleEntries[1], id: '2', date: iso }, { ...sampleEntries[2], id: '3', date: iso })
    if (i === 2) dayEntries.push({ ...sampleEntries[3], id: '4', date: iso })
    if (i === 3) dayEntries.push({ ...sampleEntries[4], id: '5', date: iso }, { ...sampleEntries[5], id: '6', date: iso })
    if (i === 4) dayEntries.push({ ...sampleEntries[6], id: '7', date: iso })
    if (i === 5) dayEntries.push({ ...sampleEntries[7], id: '8', date: iso })
    result.push({
      date: iso,
      dayName: isToday ? 'Today' : dayNames[i],
      entries: dayEntries,
    })
  }

  return result
}

const FALLBACK_CALENDAR = generateFallbackCalendar()

// ── Animation ───────────────────────────────────────────────────────────

const stagger = {
  hidden: {},
  show: { transition: { staggerChildren: 0.04 } },
}
const fadeUp = {
  hidden: { opacity: 0, y: 8 },
  show: { opacity: 1, y: 0, transition: { duration: 0.3 } },
}

// ── Component ───────────────────────────────────────────────────────────

export default function EditorialCalendar() {
  const [calendar, setCalendar] = useState<DaySchedule[]>(FALLBACK_CALENDAR)
  const [loading, setLoading] = useState(true)
  const [autoGenerating, setAutoGenerating] = useState(false)
  const [selectedEntry, setSelectedEntry] = useState<CalendarEntry | null>(null)

  useEffect(() => {
    let cancelled = false
    fetch('/api/client-zero/content-engine/calendar')
      .then((r) => r.json())
      .then((json) => {
        if (!cancelled && json.calendar) {
          // API returns 14 days — show first 7
          const days = json.calendar.slice(0, 7).map((d: DaySchedule) => {
            const todayStr = new Date().toISOString().split('T')[0]
            if (d.date === todayStr) {
              return { ...d, dayName: 'Today' }
            }
            return { ...d, dayName: SHORT_DAY_NAMES[d.dayName] || d.dayName }
          })
          setCalendar(days)
        }
      })
      .catch(() => {
        if (!cancelled) setCalendar(FALLBACK_CALENDAR)
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })
    return () => { cancelled = true }
  }, [])

  const handleAutoGenerate = async () => {
    setAutoGenerating(true)
    try {
      await fetch('/api/client-zero/content-engine/calendar', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'auto_generate_week' }),
      })
    } catch {
      // silent
    }
    setTimeout(() => setAutoGenerating(false), 2000)
  }

  if (loading) {
    return (
      <div className="grid grid-cols-7 gap-2">
        {Array.from({ length: 7 }).map((_, i) => (
          <Card key={i} className="bg-card/80 backdrop-blur-sm border-white/10 animate-pulse">
            <CardContent className="p-3 h-48" />
          </Card>
        ))}
      </div>
    )
  }

  const todayStr = new Date().toISOString().split('T')[0]

  return (
    <motion.div variants={stagger} initial="hidden" animate="show" className="flex flex-col gap-4">
      {/* ── Header ────────────────────────────────────────────────────── */}
      <motion.div variants={fadeUp} className="flex items-center justify-between flex-wrap gap-3">
        <div className="flex items-center gap-2">
          <CalendarDays className="h-5 w-5 text-emerald-400" />
          <h3 className="text-lg font-semibold">Editorial Calendar</h3>
          <Badge variant="outline" className="border-white/10 text-muted-foreground">
            This Week
          </Badge>
        </div>
        <Button
          size="sm"
          className="h-8 bg-emerald-600 hover:bg-emerald-700 text-white"
          onClick={handleAutoGenerate}
          disabled={autoGenerating}
        >
          {autoGenerating ? (
            <Loader2 className="h-3.5 w-3.5 animate-spin mr-1" />
          ) : (
            <Sparkles className="h-3.5 w-3.5 mr-1" />
          )}
          Auto-Generate Week
        </Button>
      </motion.div>

      {/* ── Legend ─────────────────────────────────────────────────────── */}
      <motion.div variants={fadeUp} className="flex items-center gap-3 flex-wrap">
        {Object.entries(TYPE_COLORS).map(([type, c]) => (
          <div key={type} className="flex items-center gap-1.5">
            <div className={`h-2.5 w-2.5 rounded-full ${c.dot}`} />
            <span className="text-xs text-muted-foreground capitalize">{type.replace('_', ' ')}</span>
          </div>
        ))}
      </motion.div>

      {/* ── Calendar Grid ─────────────────────────────────────────────── */}
      <motion.div variants={fadeUp}>
        <ScrollArea className="w-full">
          <div className="grid grid-cols-7 gap-2 min-w-[900px]">
            {calendar.map((day) => {
              const isToday = day.date === todayStr || day.dayName === 'Today'
              return (
                <div
                  key={day.date}
                  className={`flex flex-col gap-2 rounded-lg border p-2 min-h-[220px] ${
                    isToday
                      ? 'border-emerald-500/50 bg-emerald-500/5'
                      : 'border-white/10 bg-card/80'
                  }`}
                >
                  {/* Day header */}
                  <div className="flex items-center justify-between">
                    <span className={`text-xs font-semibold ${isToday ? 'text-emerald-400' : 'text-muted-foreground'}`}>
                      {day.dayName}
                    </span>
                    <span className={`text-[10px] ${isToday ? 'text-emerald-400' : 'text-muted-foreground/60'}`}>
                      {day.date.slice(5)}
                    </span>
                  </div>

                  {/* Entries */}
                  <div className="flex flex-col gap-1.5 flex-1">
                    {day.entries.length === 0 ? (
                      <div className="flex-1 flex items-center justify-center">
                        <span className="text-[10px] text-muted-foreground/40">No content</span>
                      </div>
                    ) : (
                      day.entries.map((entry) => {
                        const tc = TYPE_COLORS[entry.contentTypeId] || TYPE_COLORS.blog
                        const sb = STATUS_BADGES[entry.status] || STATUS_BADGES.scheduled
                        return (
                          <button
                            key={entry.id}
                            onClick={() => setSelectedEntry(entry)}
                            className={`w-full text-left rounded-md border p-2 transition-colors hover:opacity-80 ${tc.bg} ${tc.border}`}
                          >
                            <p className={`text-[11px] font-medium leading-tight ${tc.text}`}>
                              {entry.title}
                            </p>
                            <div className="flex items-center gap-1 mt-1.5">
                              <Badge variant="outline" className={`text-[9px] px-1 py-0 h-4 ${sb.color} border-0`}>
                                {sb.label}
                              </Badge>
                              <span className="text-[9px] text-emerald-400 font-medium">
                                +{entry.estimatedScoreGain}
                              </span>
                            </div>
                          </button>
                        )
                      })
                    )}
                  </div>
                </div>
              )
            })}
          </div>
          <ScrollBar orientation="horizontal" />
        </ScrollArea>
      </motion.div>

      {/* ── Selected Entry Detail ─────────────────────────────────────── */}
      {selectedEntry && (
        <motion.div variants={fadeUp}>
          <Card className="bg-card/80 backdrop-blur-sm border-emerald-500/30">
            <CardContent className="p-4">
              <div className="flex items-center justify-between mb-2">
                <h4 className="font-medium text-sm">{selectedEntry.title}</h4>
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-6 text-xs text-muted-foreground"
                  onClick={() => setSelectedEntry(null)}
                >
                  Close
                </Button>
              </div>
              <div className="flex items-center gap-3 flex-wrap">
                <Badge variant="outline" className={`border-0 ${(TYPE_COLORS[selectedEntry.contentTypeId] || TYPE_COLORS.blog).bg} ${(TYPE_COLORS[selectedEntry.contentTypeId] || TYPE_COLORS.blog).text}`}>
                  {selectedEntry.contentTypeId.replace('_', ' ')}
                </Badge>
                <Badge variant="outline" className={`border-0 ${(STATUS_BADGES[selectedEntry.status] || STATUS_BADGES.scheduled).color}`}>
                  {(STATUS_BADGES[selectedEntry.status] || STATUS_BADGES.scheduled).label}
                </Badge>
                <span className="text-xs text-emerald-400">+{selectedEntry.estimatedScoreGain} score gain</span>
                <span className="text-xs text-muted-foreground">Scheduled: {selectedEntry.date}</span>
              </div>
            </CardContent>
          </Card>
        </motion.div>
      )}
    </motion.div>
  )
}
